### ISSUE TITLE
403 error when attempt to stop server from UI

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/metalc#103]
I installed v1.0.0 on my mac and the same issue occurred. And it seemed to be fixed after installing the current master branch(commit 3e154d5). Might consider moving to a master branch build to fix this.

**Comment by moorepants** [comment]
There isn't enough info to know what this is about. What was installed?

**Comment by rkevin-arch** [comment]
Sounds like you got deauthenticated somehow, and so the 403 is because your old cookie no longer works. Gonna close this issue since it was forever ago.

**Comment by moorepants** [comment]
I just tested the "Stop my server" button and it worked for my user.
