### ISSUE TITLE
Install SF package in JupyterHub

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/metalc#104]
Package detail: https://cran.r-project.org/web/packages/sf/index.html

**Comment by moorepants** [comment]
Can someone knock this out quickly, since it is pretty simple?

**Comment by tkumar98** [comment]
works! 

![image](https://user-images.githubusercontent.com/53124295/71807671-b1e6c880-3020-11ea-86e9-d99c410b138f.png)
