### ISSUE TITLE
Install resonance in the default env

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#107]
https://github.com/moorepants/resonance/

This is for my class next quarter. I need #101 working for this too so I can test things out.

**Comment by tkumar98** [comment]
![image](https://user-images.githubusercontent.com/53124295/71369027-5adfee80-255e-11ea-90ea-79fa09dbe365.png)

I noticed that resonance was already installed?

**Comment by moorepants** [comment]
I need to ensure these notebooks run: https://github.com/moorepants/resonance/tree/master/notebooks some require the matplotlib jupyter extension functioning properly.
