### ISSUE TITLE
Setup monitoring of the cluster

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#11]
- Setup grafana and prometheus
- Give access to the admins

**Comment by lux12337** [comment]
Hi @Miniland1333, could we get the domain name grafana.libretexts.org for http://128.120.136.32 ? Thank you!

**Comment by Miniland1333** [comment]
I've just added the record. Let me know how grafana is since I've never used it before!

**Comment by lux12337** [comment]
Prometheus and Grafana are setup on the cluster and working. Grafana is accessible through the web with https and credentials, I will add the credentials to access grafana to the secret configuration repository later. @Miniland1333 the dashboards look amazing.
![image](https://user-images.githubusercontent.com/19236515/62001697-d0788900-b0aa-11e9-9f92-b9273f0b6ba7.png)

**Comment by moorepants** [comment]
Nice work!

**Comment by moorepants** [comment]
Close this issue when you feel you are done (probably are).
