### ISSUE TITLE
Find a way to spread load across nodes

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#110]

**Comment by lux12337** [comment]
duplicate

**Comment by lux12337** [comment]
Some relevant configuration [information](https://zero-to-jupyterhub.readthedocs.io/en/stable/reference.html#singleuser-schedulerstrategy)

**Comment by narrator0** [comment]
Kube-scheduler uses have different policies to rate each nodes. The current `configmap` we are using is  `user-scheduler` and its config is:

```
{ "name": "NodePreferAvoidPodsPriority",  "weight": 161051 },
{ "name": "NodeAffinityPriority",         "weight": 14641 },
{ "name": "InterPodAffinityPriority",     "weight": 1331 },
{ "name": "MostRequestedPriority",        "weight": 121 },
{ "name": "ImageLocalityPriority",        "weight": 11}
```

The main issue we have will be the `MostRequestedPriority` policy.

> MostRequestedPriority: Favors nodes with most requested resources. This policy will fit the scheduled Pods onto the smallest number of Nodes needed to run your overall set of workloads.

Instead of using less nodes, we will want to spread the pods as much as possible. I would suggest we can replace it with `LeastRequestedPriority`.

> LeastRequestedPriority: Favors nodes with fewer requested resources. In other words, the more Pods that are placed on a Node, and the more resources those Pods use, the lower the ranking this policy will give.

@lux12337 Do you know where `user-scheduler` is created and how can we modify it?

**Comment by lux12337** [comment]
I have enabled the user-scheduler in the config file, that along the schedulerStrategy setting of spread seemed to have done the trick. I have spawned a couple of users from the admin panel and they all were assigned to different chicks, so it seems to be working now.

**Comment by lux12337** [comment]
Closing issue as users are now spread across nodes.

**Comment by narrator0** [comment]
@lux12337 which config file did you change?

**Comment by lux12337** [comment]
I changed the config.yaml for jupyterhub

**Comment by celine168** [comment]
He changed ~/jupyterhub/config.yaml.
There’s a user-scheduler section.

Sent from Mail for Windows 10

**Comment by narrator0** [comment]
Oh, I see it. And I just checked `user-scheduler`, it did got changed to `MostRequestedPriority`. Where did you find the documentation for that?

**Comment by lux12337** [comment]
It was a combination of looking at [this](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html) and the different strategies [available](https://zero-to-jupyterhub.readthedocs.io/en/stable/reference.html#singleuser-schedulerstrategy).

**Comment by lux12337** [comment]
More [info](https://test-zerotojh.readthedocs.io/en/edit-awseks/optimization.html) on user scheduling strategies.
