### ISSUE TITLE
Limit resources for users CPU, RAM and test

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#112]

**Comment by moorepants** [comment]
It still isn't clear if this is properly working. Testing is still needed to see if users are limited if they request too many resources.

**Comment by rkevin-arch** [comment]
This is definitely working. We have resource constraints of 8GB memory and 4 CPU cores. Here's me stress testing memory, and the process got killed while it is at the 7GB memory mark, despite the host having 16GB of RAM:
![image](https://user-images.githubusercontent.com/5837628/90789927-4eae5b80-e2bc-11ea-97ba-5ca94c02d73c.png)
Here's me stress testing CPU, while all cores are utilized the utilization didn't go to 100% (which it definitely would if 8 processes are in infinite loops):
![image](https://user-images.githubusercontent.com/5837628/90790294-bf557800-e2bc-11ea-816e-804114492740.png)

**Comment by rkevin-arch** [comment]
In other news, we aren't limiting PIDs so we are vulnerable to a fork bomb, but #50 is already tracking that and I haven't found a good solution yet (there is a solution that involves setting `pod-max-pids` on all kubelets, but that involves screwing around with the config). I'll update that issue if I find anything.

**Comment by moorepants** [comment]
Sounds good. Thanks.
