### ISSUE TITLE
Weekly Security Updates Takeover

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#114]
I've been installing security updates on rooster every week, someone needs to take over this once I leave. Here are the steps to do so:

* SSH into rooster
* run `sudo unattended-upgrade -d --dry-run`, and check if there are any errors in the output
* run `sudo unattended-upgrade -d` for the actual updates

**Comment by narrator0** [comment]
@lux12337  I can do this in the future. Is there any reason we didn't use a shell script with a crontab to do this weekly?

**Comment by lux12337** [comment]
The main concern was that if an update broke rooster, then it would be good to have someone ready to fix problems. That's what we decided on in the past, but i haven't encountered any problems with updating so maybe automating could be an option? [This ](https://github.com/LibreTexts/metalc/issues/4)is the old issue that discussed this.

**Comment by narrator0** [comment]
I think I could write a shell script that reads the dry run first and send an email if anything wrong happens. Otherwise, upgrade it weekly?

**Comment by moorepants** [comment]
@narrator0 I like the idea of doing the dry run automatically and sending us a report. It could then be someone's task to log in and do the actual upgrade. The email would be the weekly reminder.

**Comment by narrator0** [comment]
I think this will be a good idea since there will be nothing to update on most weeks. But I think we don't need to send it to everyone. Maybe I can email myself only so that it doesn't spam the email list?

**Comment by moorepants** [comment]
I'd like it sent to the email list. It isn't spam, it is the purpose of the list. If people want to filter the message they can. We should get in the practice of not setting up things tied to peoples personal accounts.

**Comment by narrator0** [comment]
Sure. I will setup weekly dry run reports to the email list. And if any update available, I will do it manually.

**Comment by narrator0** [comment]
I've setup a cron job for this. I think we can close this issue. Also I'll try to include the shell script in git.

**Comment by moorepants** [comment]
Once you add the shell script and documentation on what you did to setup the cron job, you can close this. Thanks!
