### ISSUE TITLE
Monthly Scrub on ZFS Takeover

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#115]
I've been running `sudo zpool scrub nest` on our ZFS as per Richard's suggestion. Scrub checks the filesystem's integrity, and repairs any issues that it finds. This is done once a month, someone needs to take over this task or setup a cron job to do it. I would discuss with Richard first to see if there are any potential concerns with using a cron job. Also it is good to occasionally SSH into hen, and run a `zpool status` to see if there are issues with the drives.

**Comment by moorepants** [comment]
We need someone from @LibreTexts/jupyter-team to take over this task. Maybe @tkumar98?

**Comment by moorepants** [comment]
@rkevin-arch Can this be closed with your new cronjob?

**Comment by rkevin-arch** [comment]
Oh yeah, I totally forgot. Since the last email came out all clear and the cronjob worked, we can close this issue.
