### ISSUE TITLE
Install and test jupyter-archive

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#119]
This looks like a very useful extension and would be helpful for my classes:

https://github.com/hadim/jupyter-archive

It will be merged into Jupyter Lab and Jupyter Notebook eventually but we could install it until then.

**Comment by sandertyu** [comment]
What documentation could I check out in order to figure out how to remotely install this? Would this have to do with Puppet?

**Comment by moorepants** [comment]
For the exisitng cluster you edit these files: https://github.com/LibreTexts/default-env/tree/master/rich-default

Then you push it it to the staging branch and deploy to our staging instance of jupyterhub. Test it out there and then if it works, push to master, then deploy to production.

The other students can give more details on this process.

**Comment by TimStewartJ** [comment]
Added in https://github.com/LibreTexts/default-env/releases/tag/3.1.1.
