### ISSUE TITLE
Make Dockerfile Smaller

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/metalc#121]
The current Dockerfile is too large. It makes jupyterhub upgrade (not sure) slow and it make binder build slow.

**Comment by tannavee** [comment]
This may help out with figuring out what is taking up so much space: https://stackoverflow.com/questions/31627772/docker-container-size-much-greater-than-actual-size

**Comment by tannavee** [comment]
discussed in the meeting: 

- build the docker image once, and save the apt list values as an environment.yaml
- this can help with a faster build for Thebelab

**Comment by celine168** [comment]
Useful link: https://hackernoon.com/tips-to-reduce-docker-image-sizes-876095da3b34
Please feel free to work on this issue too by the way

**Comment by celine168** [comment]
- [ ] Go into the current Docker container, retrieve a requirements.txt/package-list.txt, then import it into the Dockerfile and install only the pinned versions
- [ ] Less layers?
- [ ] Making sure there are clean statements after each statement
- [ ] Possibly combine conda statements
- [ ] Maybe add a Dockerfile linter if there is one

**Comment by moorepants** [comment]
One particular thing is that we are installing texlive-full, which is helpful for a full latex setup, but there is a ~ 2Gb texlive-fonts-extra that probably isn't needed. You could install everything texlive-full does except that package to save 2GB.

**Comment by celine168** [comment]
I am experimenting with pointing the CKEditor plugin to our Dockerfile and our own Binder.
It's a little hacky (but it works) by making the Dockerfile like this: https://github.com/LibreTexts/default-env/blob/fix/ckeditor-condense/Dockerfile

If it's the first time that the plugin is requesting the kernel on a node that doesn't have the Docker image, it will take about 5 minutes for it to pull the image (a lot better than 1+ hour). If the node already has the image, it should only take a few seconds.
The ~5 minutes that it takes to pull the image could probably be reduced by squashing the image somehow or creating less layers, the former of which I read online does not work but I'm trying it out right now. 
When someone changes languages in the plugin, Binder tries to build a new image. I would love if there was an option in Thebelab to change the kernel language without actually requesting a new kernel so we could save time in this part as well.

**Comment by moorepants** [comment]
Do you know why it has never taken 5 minutes or more on the JupyterHub? What makes it take so long on binder but not on JupyterHub?

**Comment by moorepants** [comment]
> I would love if there was an option in Thebelab to change the kernel language without actually requesting a new kernel so we could save time in this part as well.

That sounds like an opportunity to submit a PR to thebelab.

**Comment by celine168** [comment]
When you upgrade JupyterHub, the images that are needed for the environments get pulled beforehand (but they don't get built, aka the Dockerfile doesn't get run) and the image is ready on all nodes after the upgrade.

On Binder, it builds a new image from the Dockerfile, which takes a while. The Dockerfile I linked above means to mimic what JupyterHub does ("pulling the image" without actually building it from scratch). 

And yes, I asked Thebelab and they don't have the functionality that of changing the kernel language. So we may implement it and submit a PR

**Comment by moorepants** [comment]
Interesting. I didn't know that was how things work. So if binder has this extreme slowness, maybe it is a bad decision to use default-env with binder. Maybe we just have to have separate small dockerfiles for binder (maybe using the existing jupyter ones is sufficient). But this then leaves the page authors not having packages they need. They would have to have a custom enviornment.yml (or other repo2docker config) to build their custom setups. This puts a technical burden on the authors of each page, but it may be the only realistic option.

The only other thing I can think of is if we can modify/configure/setup binder to have the default-env prebuilt for use. Seems like we should be able to. We build it each time we upgrade jupyterhub and then we ensure binder has access to it, so it loads quickly. Seems like there must be a way to do that.

**Comment by celine168** [comment]
I believe that if JupyterHub upgrades and sees an image of the same tag, it will use the Docker image locally, regardless of whether it was updated online in DockerHub under the same tag. (Like if we use `latest` and updated the image under `latest` in DockerHub, JupyterHub would still use the older local version and I suspect that Binder would do the same). 

I'm still trying to find a way in that Dockerfile to pull the image based on the SHA tag of the current Docker image that JupyterHub is on (aka the master branch SHA tag of default-env) or to pre-pull the images beforehand.

The first option is a good alternative.

**Comment by moorepants** [comment]
This is probably worth asking in the jupyter discourse.

**Comment by celine168** [comment]
If we do use an image that's already on our nodes (pulled via JupyterHub) with something like this: https://github.com/celine168/default-env-condensed/blob/master/Dockerfile as our BinderHub, fetching the base image via
```
ARG BASE_CONTAINER=libretexts/default-env:82bae0bca736
FROM $BASE_CONTAINER 
```
takes ~30 seconds-ish. This is only if the node hasn't run the above commands yet. Afterwards, it should take slightly less time to launch the server.

**Comment by celine168** [comment]
I opened a Discourse post here: https://discourse.jupyter.org/t/pre-building-images-on-binderhub/4325

**Comment by moorepants** [comment]
@rkevin-arch and @sandertyu One more issue on the dockerfile size.

**Comment by rkevin-arch** [comment]
Our new repo2docker setup is around 22GB. Here's a very very rough approximate breakdown of all the things taking up space:
SageMath and its kernel: 10GB
JupyterLab extensions: 0.4GB
RStudio and Shiny: 1GB
All other conda packages in our environment: 4GB
Apt (mostly texlive-full and octave): 4GB
Base miniconda installation with JupyterLab: 1.3GB
Julia and packages: 0.6GB
Base OS: 0.7GB
Our setup is now a lot easier to maintain thanks to repo2docker, but the image size is still very big and the build takes around an hour. This might be fine since it just means slower turnarounds for updating the environment, and especially if we run an internal registry pushing/pulling the images won't be a big deal. I'm gonna leave this issue open to see what @moorepants thinks.

**Comment by rkevin-arch** [comment]
Any thoughts on this? We did make the Dockerfile smaller by migrating over to repo2docker, which is more maintainable. Our new image is still huge, though. It looks like most of it is considered necessary. We can probably get rid of SageMath if conda can actually install it, but I doubt that's going to happen soon. If this is considered acceptable, I'm going to close it.
As for using on binder, the mybinder.org implementation builds the image once and reuses it, so the slowness mostly comes down to pulling the images. We can avoid this by using our own binder and configuring it to pre-pull our specific image.

**Comment by moorepants** [comment]
It turns out that the large size of texlive-full comes from all the different language packs (if I remember correctly). We could remove the language packs for the less widely used languages and only add them when requested by users (if it happens). I think that cuts 1 or more GB from that package. We just have to deal with Sagemath as is till it is conda installable. Or maybe in ubuntu 20.04 the apt pacakge would be up-to-date enough to use it.

**Comment by moorepants** [comment]
This is the relevant texlive note. Its not the languages it is the fonts:

> One particular thing is that we are installing texlive-full, which is helpful for a full latex setup, but there is a ~ 2Gb texlive-fonts-extra that probably isn't needed. You could install everything texlive-full does except that package to save 2GB.

**Comment by rkevin-arch** [comment]
From what I can tell, texlive-fonts-extra takes 1GB instead. Is there a reason why we are doing `texlive-full` rather than just `texlive-latex-extra` which includes a bunch of recommended packages?

**Comment by moorepants** [comment]
We are only doing texlive-full because it provides everything users might need. In my personal use I've found that the font packages are unnecessary, but I don't do anything special with fonts. We don't know what users need. I'm fine with installing less, but it seemed that removing the fonts is the real space saver, so leaving everything else let's people have the packages they may need.

**Comment by sandertyu** [comment]
Everything installed by `texlive-full` should be outlined on this page; https://packages.ubuntu.com/focal/texlive-full

There are a few other dependencies installed which involve fonts as well, as seen in this image;

![image](https://user-images.githubusercontent.com/59950537/90828762-65bc7000-e2f3-11ea-8c49-77f5f187d22e.png)

Out of all the font packages, `texlive-fonts-extra` is by far the biggest (as mentioned), with the rest all being under 100MB. If we want to remove `texlive-fonts-extra`, should we remove all of those other font packages as well, or just remove the single 1? Also to note is that we would have to individually add every single one of the other packages from that link to apt.txt, which makes it cluttered but probably isn't an issue.

**Comment by rkevin-arch** [comment]
Here's the list of packages we came up with:
```
biber
chktex
cm-super
context
dvidvi
dvipng
feynmf
fragmaster
info
lacheck
latexdiff
latexmk
lcdf-typetools
lmodern
prerex
psutils
purifyeps
t1utils
tex-gyre
texinfo
texlive-base
texlive-bibtex-extra
texlive-binaries
texlive-extra-utils
texlive-font-utils
texlive-fonts-recommended
texlive-fonts-recommended-doc
texlive-formats-extra
texlive-games
texlive-humanities
texlive-humanities-doc
texlive-lang-english
texlive-latex-base
texlive-latex-base-doc
texlive-latex-extra
texlive-latex-extra-doc
texlive-latex-recommended
texlive-latex-recommended-doc
texlive-luatex
texlive-metapost
texlive-metapost-doc
texlive-music
texlive-pictures
texlive-pictures-doc
texlive-plain-generic
texlive-pstricks
texlive-pstricks-doc
texlive-publishers
texlive-publishers-doc
texlive-science
texlive-science-doc
texlive-xetex
tipa
vprerex
xindy
```
Compared to texlive-full itself, the following packages are removed:
- latex-cjk-all (chinese-japanese-korean package)
- texlive-fonts-extra, texlive-fonts-extra-doc, texlive-fonts-extra-links (extra fonts)
- all texlive-lang-* packages except texlive-lang-english (some of them are still installed, such as texlive-lang-greek which is needed by texlive-science to display greek symbols, but this saves some space)

This saves around 2GB of disk space. Let us know if this is acceptable.

**Comment by moorepants** [comment]
I'm fine with starting with that list. We can add things if people request more.

**Comment by rkevin-arch** [comment]
The repo2docker setup is merged into master and is now our official setup, so this issue is resolved.
