### ISSUE TITLE
All packages in environment.yml should be pinned to specific versions

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#124]
We should pin the packages in the default env to specific versions that function together. We can upgrade these just like we will be updating packages on ubuntu, i.e. carefully. Periodically we can test a compatible environment and upgrade safely.

**Comment by tannavee** [comment]
@celine168 I think this was done this past quarter, when you created the environment.yml file?

**Comment by celine168** [comment]
Yes, I'm just waiting for the OK to merge the PR. I would like to automate some part of this process though, as Jason outlined above. I'm guessing GitHub Actions might be good for this though I haven't worked with it before so it would take some time experimenting.

**Comment by moorepants** [comment]
Seems you are now doing this, can this be closed?
