### ISSUE TITLE
Consider using Chartpress

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#126]
There is a program called [chartpress](https://github.com/jupyterhub/chartpress) which allows automatic Docker builds and more. We should consider implementing it if it will modify `config.yaml` the way we want it to (or disable that feature entirely).

**Comment by moorepants** [comment]
What specifically will this help with? I didn't understand with a quick read through of the readme.

**Comment by rkevin-arch** [comment]
Chartpress really helps if you are creating your own helm charts. If we want it for automated Docker builds for JupyterHub, it isn't worth it IMO since the helm chart already exists, and we also have a repo2docker setup which should automate Docker builds easily (and use something like Travis).
