### ISSUE TITLE
Make conda packages for...

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#127]
These are things we are installing from git in the dockerfile which need conda packages:

- [ ] https://github.com/PAIR-code/facets (did anyone request this?)
- [ ] rstudio (should be conda installable, no?)
- [ ] https://github.com/cxhernandez/ipymol
- [x] pypdb (already exists: https://anaconda.org/conda-forge/pypdb)
- [x] biopandas (already exists: https://anaconda.org/conda-forge/biopandas)
- [x] pygmt (see: https://github.com/conda-forge/staged-recipes/pull/11468)
- [x] mordred (already available: https://github.com/conda-forge/mordred-feedstock)
- [x] rdkit (already available: https://github.com/conda-forge/rdkit-feedstock)
- [x] boost (already available: https://github.com/conda-forge/boost-feedstock)
- [x] freeglut (already available: https://github.com/conda-forge/freeglut-feedstock)
- [ ] pymol (this is potentially problematic, it isn't clear it is fully open source, here is a recipe: https://github.com/PhyreEngine/conda-pymol-opensource)

**Comment by moorepants** [comment]
The facets repo doesn't seem to be packaged in any package manager. So I think we should remove it unless someone is actually somehow using our installation. This is something that users can install on their on if they want to support it. It is not in our interest to support something like this.

The pypdb and biopandas should be switched from pip to conda

I think we should remove ipymol and likely pymol too. If someone wants to make a conda-forge pymol package we could support it but I dont' want to install anything from channels other than defaults and conda-forge on default-env.

Not sure yet about rstudio.

**Comment by celine168** [comment]
Noting here as a reminder to self, also work on getting rid of other channels:
  - samoturk
  - mordred-descriptor
  - rdkit

**Comment by moorepants** [comment]
The pygmt package is now available: https://github.com/conda-forge/pygmt-feedstock

**Comment by moorepants** [comment]
Note that the biopandas feedstock is now at 0.2.5, we should switch it to conda forge.

**Comment by moorepants** [comment]
I also see where these packages came from: https://chem.libretexts.org/Courses/Intercollegiate_Courses/Cheminformatics_OLCC_(2019)/1._Introduction/1.05%3A_Installing_Python These people have been using the hub, so we should check with them before removing things. But this is quite the mess of an install process and pulls from lots of unofficial sources.

**Comment by moorepants** [comment]
I've updated biopandas, pypdb, pyshtools, and xmltodict here: https://github.com/LibreTexts/default-env/pull/43/files

**Comment by moorepants** [comment]
Here are some packages that are installed from non-conda-forge and non-defaults:

```
jovyan@jupyter-moorepants-40gmail-2ecom:~$ conda list | grep mordred
mordred                   1.2.0              pyhe5148d4_0    mordred-descriptor
jovyan@jupyter-moorepants-40gmail-2ecom:~$ conda list | grep rdkit
boost                     1.63.0           py36h415b752_1    rdkit
rdkit                     2017.09.1                py36_1    rdkit
jovyan@jupyter-moorepants-40gmail-2ecom:~$ conda list | grep samo
freeglut                  3.0.0                         4    samoturk
pymol                     1.9.0.0                  py36_0    samoturk
```

**Comment by rkevin-arch** [comment]
For our repo2docker setup:
- facets (not sure who requested it either, but seems to be in the default scipy notebook so maybe we should keep it) is installed via pip
- rstudio is installed via apt automatically by repo2docker (no intervention required)
- pymol/ipymol has been dropped

Since our repo2docker setup is using conda-forge as its only conda channel, I feel like we can close this issue.
