### ISSUE TITLE
RStudio error message

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#129]
I get this on the Rstudio page:
```
03 Sep 2019 00:33:12 [rsession-jovyan] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
```
![2019-09-20_16-10](https://user-images.githubusercontent.com/276007/65363539-56074980-dbc1-11e9-86b0-db5d5a10e63d.png)

**Comment by rkevin-arch** [comment]
Googling `hadabend` gave me absolutely no results, and I can't figure out what the problem could be. Hopefully a higher version of R and jupyter-rsession-proxy have solved this issue. If this happens again, we can reopen and revisit this.

**Comment by moorepants** [comment]
This still occurs. I guess it is something specific to my user. Leaving open, since it is still an issue.

![Selection_732](https://user-images.githubusercontent.com/276007/90475059-001b8880-e127-11ea-804f-aeba25ec6d80.png)

**Comment by moorepants** [comment]
Some clues here: https://community.rstudio.com/t/continuous-crash-on-rstudio-server/19302/5

**Comment by moorepants** [comment]
I did `rm -r .rstudio` and restarted the rstudio session and it is fixed. Something was corrupt in my user session data.
