### ISSUE TITLE
Setup Grafana automatic alerts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#13]
Alerts for certain server issues. Could be worth asking other binder/jupyterhub people how they do this and what are the important alerts to have emailed to us.

**Comment by moorepants** [comment]
- [x] Setup basic alerts for the cluster, alerts are sent via Slack and Email when:
    - [x] jupyter.libretexts.org goes down.
    - [x] Ping is too high for jupyter.libretexts.org .
    - [x] The cluster CPU/cores/RAM utilization exceeds 80%.
    - [x] Single node CPU/RAM utilization exceeds 90%.
    - [x] If a node goes down/offline.

**Comment by lux12337** [comment]
Email notifications have been turned off for the moment as Grafana was producing too many email notifications. I wasn't expecting so many fluctuations in the data, I have adjusted the thresholds to be less sensitive.
