### ISSUE TITLE
Clean up Dockerfiles

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#130]
There are too many `apt update and install`'s so those could probably get consolidated. I also want to add more comments.

Right now, the Dockerfile for the default environment takes at least an hour to build, so if consolidation doesn't decrease the build time, then hopefully splitting up the Dockerfile will.

**Comment by moorepants** [comment]
Also, you could break the dockerfile into two: a base one with the apt install commands and then one for the conda install commands.

**Comment by moorepants** [comment]
@rkevin-arch @sandertyu Note that breaking our deafult-env dockerfile into multiple files could help with build times. It could be worth separating the apt installed things and the conda installed things into two files, for example.

**Comment by rkevin-arch** [comment]
Closing this since it's no longer an issue with our new repo2docker setup.
