### ISSUE TITLE
chick5, large memory use, NotReady

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#132]
chick5:

```
chick5    NotReady,SchedulingDisabled   <none>   246d   v1.14.0   10.0.0.105    <none>        Ubuntu 18.04.2 LTS   4.15.0-51-generic   docker://18.9.5
```

![Selection_688](https://user-images.githubusercontent.com/276007/74487213-c619b300-4e73-11ea-88e2-6b85ca79342c.png)

What state is this in? If disabled why is it using so much memory?

**Comment by celine168** [comment]
Some pods will still run on chick5 as they are considered "critical" by Kubernetes. I've noticed that existing pods that were created before disabling scheduling will also continue to run.

**Comment by rkevin-arch** [comment]
Chick5 is removed from the cluster since forever, and it doesn't look like we have plans to join it back to the cluster, so closing this issue for now.
