### ISSUE TITLE
AIDE logs taking up too much space in /run folder

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#134]
The `/run` partition on rooster, (which you can see by running the command `df`) was at 100% use, which blocked certain commands from running, including blocking resolving domain names, editing `/etc/resolv.conf`, and running `docker build`. 

After some searching, mostly by using `sudo du -d1 -h /run` among other sommands, I found that `/run/aide/cron.daily.old.kj0WVYx28N/cron.daily/arunlog` was taking up all the space. I ran `sudo rm` on the file to fix the problem.

Richard suggested using logrotate to fix the issue of logs growing too large in size.

**Comment by moorepants** [comment]
We could also disable AIDE until we understand how to manage the logs.

**Comment by celine168** [comment]
I have disabled it.

**Comment by celine168** [comment]
I added AIDE logs to logrotate (in `/etc/logrotate.d/aide`) and reenabled AIDE a while ago. After waiting for a few weeks, the logs seem to rotate now.

**Comment by moorepants** [comment]
Great!
