### ISSUE TITLE
ipymol is outdated, requires installation from GitHub repository

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#135]
The [ipymol](https://pypi.org/project/ipymol/) package on pip is a bit outdated. It's currently at v0.5 but I found that the package doesn't work when installed directly from pip. The [GitHub repository](https://github.com/cxhernandez/ipymol) for this package is more up to date and it did work at one point when I installed it to our Default Environment.

However, recent installs of the package through the repository doesn't seem to work. It could be caused by the specific conda environment we installed (since ipymol is installed after the conda environment is). The package seems generally inconsistent.

Ehren Bucholtz wants the package `pymol` installed, it isn't clear yet whether he also wants `ipymol`, which allows using pymol in Jupyter Notebooks. I have emailed him about it.

**Comment by moorepants** [comment]
I'd just just tell them, we are going to remove ipymol because we can't support non-official releases.

**Comment by moorepants** [comment]
FYI, just saw this: https://github.com/arose/nglview (looks more well maintained than ipymol). Not sure if it is the same functionality though.

**Comment by moorepants** [comment]
We should remove ipymol.

**Comment by moorepants** [comment]
It also seems like pymol is a proprietary software (or pseudo open source). Probably best for us to remove all of this.

**Comment by rkevin-arch** [comment]
We have decided to drop support of pymol/ipymol for our new repo2docker environment.
