### ISSUE TITLE
Fixing two user accounts with a 504 Gateway Error

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#139]
## Problem
Two users today had trouble logging in; at least one user received the error: 
```
"504 Gateway Time-out"

"nginx/1.13.12"
```
Note that this is a very similar issue to #50.

## Solution
We ran the upgrade script first (`./upgrade.sh`). Since I realized it took a while to upgrade, I deleted the `hub-xxx` pod to reset the Hub directly (which upgrading does, but running the upgrade forces pulling the Docker images from DockerHub first, which takes a while).
Afterwards, the user accounts were able to spawn (which you could check through spawning their server in the Admin tab).

**Comment by rkevin-arch** [comment]
This is just the hub being unresponsive, and we don't know the root cause (could just be a fluke). We can make a new issue if this happens again.
