### ISSUE TITLE
Install the hardware enablement kernel on the current cluster

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#141]

**Comment by celine168** [comment]
For more information:
* What is hardware enablement kernel? https://askubuntu.com/questions/248914/what-is-hardware-enablement-hwe
  "Hardware Enablement (HWE) is about catching up with the newest hardware technologies. Ubuntu will offer at least two kernels: the General Availability (GA) kernel, i.e. the most stable kernel, which does not get updated to point releases; and the Hardware Enablement (HWE) kernel, i.e. the most recent kernel released."

* How to switch/install: https://askubuntu.com/questions/887123/can-i-switch-to-hwe-kernel-after-installation

**Comment by celine168** [comment]
This has been installed on all of the chicks, including master (chick0).
