### ISSUE TITLE
Use Puppet For Automating The Cluster setup

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#142]

**Comment by moorepants** [comment]
Maybe this shouldn't be "instead of ansible" but it should be "use puppet for automating the cluster setup". Ansible will likely still be used for the Jupyter stuff, right? Essentially, puppet would eventually run the Jupyter ansible steup scripts. This way you can continue to use the scripts developed by project jupyter.

**Comment by tannavee** [comment]
- [ ] create Puppet on Vagrant
- [ ] install Kubernetes Module 
- [ ] create setup for Cluster

**Comment by celine168** [comment]
Just letting you know, we won't be pushing the Kubernetes output .yaml files up to here since they contain private keys. I'll push mine up to the private repo.

**Comment by celine168** [comment]
FYI: There's a private control repo under our org now.

**Comment by rkevin-arch** [comment]
We now have https://github.com/LibreTexts/protogalaxy which should solve this issue. We should probably have one central issue tracking everything Puppet related for galaxy, but I'll leave this open in case this is the only issue related to it.

**Comment by moorepants** [comment]
Consolidating issues regarding in the birth of galaxy is fine.

**Comment by sandertyu** [comment]
We have a [control-repo](https://github.com/LibreTexts/galaxy-control-repo) which automates the setup of the galaxy cluster, implements the protogalaxy puppet module (see `Puppetfile`), and contains all of the kubernetes resources that we have added so far in `/kubernetes/`. I think this issue can be closed, and we can use that repo for further galaxy tracking.

**Comment by moorepants** [comment]
Sounds good. Note that we agreed that all issues should be in metalc long back. If you'd like to revisit that, we should discuss at the next meeting.
