### ISSUE TITLE
Did we lose the Grafana alerts again?

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#143]
I'm not seeing the custom alerts in Grafana. I think Grafana may have went down and we lost the custom settings. Can someone check into this? Luigi left a way for us to load the alerts back via json file (I think).

**Comment by celine168** [comment]
Yes, we did. I can't find the json files myself so I'm asking Luigi where he put them.

**Comment by moorepants** [comment]
They might be in the private config repo.

**Comment by moorepants** [comment]
@celine168 I think this should be a high priority. The alerts were the only way I (and maybe you all) new that things were going wrong the last two quarters. Right now, we have no warning signals.

**Comment by celine168** [comment]
I'm fixing it now.

**Comment by celine168** [comment]
I'll complete it a bit later in the day when I get the Slack permissions from Luigi. Looks like all of the alerts got deleted somehow.

**Comment by moorepants** [comment]
Ok, thanks for the update. Can you make sure the necessary files and documentation for how to fix this is present after you make the fix too? I'm not sure if Luigi did that.

**Comment by celine168** [comment]
Just another update: I figured out how to import the Node Alerts back in and email alerts should be back on for individual nodes, but there are two other dashboards (cluster and DNS/pinging) that got lost. I'll try to rebuild them.

**Comment by celine168** [comment]
Grafana alerts should be back up on email and Slack now. I will extend the documentation on this once I get the chance.

**Comment by celine168** [comment]
Added more Alerting documentation via https://github.com/LibreTexts/metalc/commit/5c09a8a8887523d5c89f68314b1c696fc1da64fc, closing.
