### ISSUE TITLE
Unable to Stop Server in Hub Control Panel

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#148]
When I attempt to stop my own server in the Hub Control Panel, I receive a 404 API Server error and my pod doesn't delete itself when it's supposed to.

![image](https://user-images.githubusercontent.com/22624020/79249243-d3cac500-7e31-11ea-872a-fe1e22945bb3.png)
This would be useful to fix so users could try restarting servers themselves. Not sure if this is happening to only me or all users.

**Comment by celine168** [comment]
Interestingly, we are able to stop their servers from the admin control panel. There are also similar errors when trying to generate API tokens under the token tab.
I read somewhere that this issue could arise if there are Docker containers: https://jupyterhub.readthedocs.io/en/0.6.1/troubleshooting.html#get-hub-api-authorizations-cookie
There is also a possible solution with upgrading the database, which I do not want to do since if it doesn't work, we may have to start from a fresh user database.

**Comment by celine168** [comment]
Most likely a database error:
https://discourse.jupyter.org/t/clean-login-database/1150
https://discourse.jupyter.org/t/hub-shutdown-causes-error/1190

**Comment by celine168** [comment]
Just noticed I'm getting a similar error in the Staging Hub as well. Either there are conflicts with the production hub or this is a JupyterHub-wide error?

**Comment by rkevin-arch** [comment]
I haven't seen this issue before, and that 403 for the DELETE request makes me think the user might have been logged out due to inactivity (?). Tentatively closing this issue until we see it again.
