### ISSUE TITLE
Set up user resourse limits

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#15]
Someone needs to find out what limits other jupyter/binder setups give and we can copy that as a start.

- [x] CPU
- [x] Memory
- [x] Drive space (500 MB per user for now)
- [x] Document how many users we can support at min limits

**Comment by lux12337** [comment]
The resources available per node are:
CPUs: 6 cores
RAM: 16GBs

**Comment by lux12337** [comment]
Copying the [pangeo](https://github.com/pangeo-data/pangeo-binder/blob/staging/pangeo-binder/values.yaml) deployment for Binderhub:
CPU: 
limit: 4
guarantee: 1
MEMORY:
limit: 8G
guarantee: 1G
These are the current resource limits.

**Comment by lux12337** [comment]
Disk storage has been set to 500MB for BinderHub and JupyterHub

**Comment by celine168** [comment]
Since we give a minimum of half a core per user and we have about 10 nodes, the current cluster should support about 100 concurrent users. 
Some of the CPU is reserved for other processes such as monitoring, running the hubs for Binder and Jupyter, etc., so we rounded the number of users down.

**Comment by moorepants** [comment]
How many accounts can we support based on hard disk space?

**Comment by moorepants** [comment]
Please add these setting and # user stats to the documentation somewhere.

**Comment by lux12337** [comment]
Based of the current setup, with the nfs server being on rooster, there is 2TB of storage available: 
2TB / 500MB = 4000 users
However, once we have a physical NFS server setup, we can add way more storage if we need to.

**Comment by celine168** [comment]
Added user stats to bare metal documentation.

**Comment by moorepants** [comment]
Great, thanks!
