### ISSUE TITLE
Use only conda-forge

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#151]
Transferred from https://github.com/LibreTexts/default-env/pull/33

We are currently using these channels:
  - mordred-descriptor
  - rdkit
  - conda-forge
  - defaults

and we wish to conda-forge and defaults.

**Comment by moorepants** [comment]
Also, the order of the channels is import, you want everythign to be installed from conda-forge and then defaults if it can't be found in conda-forge. Here are some tips: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

The strict_priority things would be nice to have too.

**Comment by moorepants** [comment]
I'm pretty sure mordred and rdkit channels can be removed as the packages they are supplying are in conda forge. See #127

**Comment by sandertyu** [comment]
I can create a new image through editing environment.yaml with channel priority set to strict, conda-forge moved above defaults, and with the other channels removed. Is there a quick or efficient way to make sure that all the current packages remained installed if I test that out? @moorepants

**Comment by moorepants** [comment]
I've been submitting package feedstocks to conda-forge (slowly). Ideally, we get the needed packages built on conda-forge, then remove these other channels. Search metalc for more info on this. I think we have two or three open related issues.

**Comment by moorepants** [comment]
https://github.com/LibreTexts/metalc/search?q=conda-forge&type=Issues

**Comment by sandertyu** [comment]
I went through our installed packages and searched for ones which can be replaced with conda-forge equivalents. The picture below shows all of these packages.

![altchannels](https://user-images.githubusercontent.com/59950537/86869901-3d9ee780-c08c-11ea-9d5c-814888f7a2fc.PNG)

### Packages that can be replaced with conda-forge equivalents
- biopandas (Available via [conda-forge](https://anaconda.org/conda-forge/biopandas), currently using `pypi`)
- pypdb (Available via [conda-forge](https://anaconda.org/conda-forge/pypdb), currently using `pypi`)
- pyshtools (Available via [conda-forge](https://anaconda.org/conda-forge/pyshtools), currently using `pypi`)
- xmltodict (Available via [conda-forge](https://anaconda.org/conda-forge/xmltodict), currently using `pypi`)
- mordred (Available via [conda-forge](https://anaconda.org/conda-forge/mordred), currently using `mordred-descriptor`)
- freeglut (Available via [conda-forge](https://anaconda.org/conda-forge/freeglut), currently using `samoturk`)
- boost (Available via [conda-forge](https://anaconda.org/conda-forge/boost), currently using `rdkit`. Sidenote, `boost-cpp` is also availble on version 1.73 from conda-forge, current is 1.72)

### Packages without a conda-forge equivalent
- ipymol (Based on #127 , can this be removed? Currently dependent on `pypi`)
- pyqt5-sip (dependent on `pypi`)
- pyqtchart (dependent on `pypi`)
- pyqtwebengine (dependent on `pypi`)
- pymol (Similar to ipymol, can this be removed? Currently dependent on `samoturk`)
- rdkit (installed via itself, only available by `rdkit`)

If we install all of the packages from conda-forge which currently can be, then we can remove the `mordred-descriptor` channel. Removing pymol will allow us to remove the `samoturk` channel. The remaining packages (all dependent on pypi) would be
- ipymol (possibly removed)
- pyqt5-sip
- pyqtchart
- pyqtwebengine

Let me know if you like me to do anything with this.

**Comment by moorepants** [comment]
These pymol relate packages were requested by Bob Bedford's team at the University of Arkansas. We should reach out to them and try to figure out if they are actually using these packages. If they are we can figure out the best way to support them.

**Comment by moorepants** [comment]
The pyqt are depenencies of pymol I think.

You can switch any packages you can to conda forge now.

**Comment by sandertyu** [comment]
> You can switch any packages you can to conda forge now.

My plan for going about this was to just remove the `mordred-descriptor` channel, reorder the channels and set the channel priority to strict, and then let conda do its work. However, there currently is [no way to set the channel priority to strict in environment.yml](https://github.com/conda/conda/issues/8675), and the only thing I could find about setting it in the Dockerfile was [this](https://github.com/databricks/containers/blob/b3c712bdb030565d786b3dbf9253552fff029caa/ubuntu/python/Dockerfile#L29). We may be able to use the Dockerfile method, but I'm not sure what the path needs to be. I assume the path given for the .condarc file from `conda info` within jupyter.libretexts.org is not the one we want to change. 

![conda-info](https://user-images.githubusercontent.com/59950537/86880197-42ba6180-c0a1-11ea-9615-948571b2ff9d.PNG)

**Comment by j-wags** [comment]
[RDKit is available on conda-forge](https://anaconda.org/conda-forge/rdkit/files). Though it looks like you're on a pretty old version (2017), whereas build are only available on conda-forge for mid-2018 and later.

**Comment by rkevin-arch** [comment]
Our new repo2docker setup is indeed only using conda-forge, so this is now resolved.
