### ISSUE TITLE
Signing out while inside R-Studio

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#152]
I figured out how to get an R-Studio spawner; however, there is no easy way to sign out or switch back to the JupyterLab environment while inside R-Studio (except by modifying the URL to `lab`).

**Comment by celine168** [comment]
I can add an R-Studio spawner with small note in the spawner's description to manually switch to `/lab` in the URL in case if anyone wants to access R-Studio and can't figure out how to get out of it.

**Comment by moorepants** [comment]
We could ask Richard if the button is sufficient. I like that. It opens it in the new tab, but you still have access to the jupyter lab interface.

**Comment by celine168** [comment]
The staging JupyterHub shows what it looks like with the RStudio Spawner as well, if you want a comparison.

**Comment by rkevin-arch** [comment]
We should ask users to open RStudio in the JupyterHub launcher. This will preserve the JupyterHub interface, allowing them to spawn new notebooks / sign out. Normal users would see the JupyterHub bar and be able to logout, and power users who change the URL manually to `/rstudio` would also know how to change it back to `/lab`, so this shouldn't be an issue.
