### ISSUE TITLE
Remove the demo version of Thebelab on LibreTexts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#153]
This page is still available and needs to be removed:

https://chem.libretexts.org/Under_Construction/Purgatory/5.2%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)

I'm not sure how to remove the actual code that enables thebelab, but that needs to go too.

**Comment by Miniland1333** [comment]
The page has been made private and since it is in Purgatory is highly unlikely to be reinstated.
