### ISSUE TITLE
Create a LibreTexts page in construction guide that points users to the documentation for each kernel.

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#157]
Each of the kernels we are supporting have some set of documentation from the creators of that kernel. It would be helpful to have a page that points LibreText page integration users to this documentation and to the support channels. An example use case is the Sierra College professor that asked about how the C++ xeus cling works. Or how to plot something, etc. Many of these support needs should be directed towards the projects. We'd like our support to focus on the editor, thebelab, and default installed packages.

**Comment by moorepants** [comment]
@sandertyu It would be useful to point Hub users and LiberText page users towards the documentation for the different kernels we support and JupyterHub/Lab in general. This info belongs in the Hub FAQ and on the LibeTexts construction guide.

**Comment by mandeepika** [comment]
Just to make sure what needs to be done. So, there should be a page added to the Libretexts construction guide under the [Jupyter Notebooks](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements) section. This will point the users to this [link](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) (I found it on jupyterhub FAQ page), which has the full list of Jupyter kernels. Additionally, we need to point them to JupyterHub/Lab. Is that all or am I missing something?

**Comment by sandertyu** [comment]
> Just to make sure what needs to be done. So, there should be a page added to the Libretexts construction guide under the [Jupyter Notebooks](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements) section. This will point the users to this [link](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) (I found it on jupyterhub FAQ page), which has the full list of Jupyter kernels. Additionally, we need to point them to JupyterHub/Lab. Is that all or am I missing something?

That's probably a good place to start. You'll want to login with chem libretexts jupyterteam credentials, and then you can create a new page from [this one ](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Installing_custom_packages). This will create a new page in the `5.2` section. Feel free to start and we can all review whenever you would like to share.

**Comment by mandeepika** [comment]
Let me know what needs to be added [here](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Installing_custom_packages/Documentation_of_Supported_Kernels).

**Comment by moorepants** [comment]
That's a good start, but it could be a bit more helpful if you link to the documentation directly for each of the kernels we support. We get questions from users of libretexts that demonstrate they aren't aware of how jupyter works or how jupyter works for their specific kernel. So for example, if I want to use Julia then this is the most relevant page for a Julia user to start at: https://julialang.github.io/IJulia.jl/stable/manual/usage/. We're looking for the most "official" explanation for a user of the kernel, i.e. what magics are available, how to get images to display as cell output, etc. We'd probably want to avoid pointing them to anything heavily about installing the kernels, because we already have done that for them. Another example is that a C++ libretexts author wanted to run g++ commands to compile code, but that's not how the C++ kernel works, so they were confused. We should point them to some basic explanation of how to use the C++ kernel.

**Comment by mandeepika** [comment]
Let me know if something else needs to be added [here](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Installing_custom_packages/Documentation_of_Supported_Kernels).
As suggested, I directed the users to the links which contain information on the usage of the kernels rather than the whole project or installation processes. Some kernels did not really have an "official" documentation, but there were example notebooks which give tutorials and introduction to the kernel. So, I linked those in the guide.

**Comment by moorepants** [comment]
Looks good, but we only need to point to documentation for the kernels we support. It looks like you may have spent some time to find each one, but could your remove all links but the ones we support. Sorry :(

**Comment by mandeepika** [comment]
Oh haha oops! Yes I can go ahead and do that. But  just to be sure how do I know which ones out of the [whole list](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) are we currently supporting?

**Comment by moorepants** [comment]
You can see what we have installed in the default-env repo and then we have specific kernels enabled in the ckeditor thebe plugin. I think that is the same list at the moment. I think they are Python, Julia, Sage, C++, R, and Octave.

**Comment by mandeepika** [comment]
Took out the ones we don't support: [link](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Installing_custom_packages/Documentation_of_Supported_Kernels).

**Comment by moorepants** [comment]
Fabulous! This issue is closed! Thanks @mandeepika !
