### ISSUE TITLE
Grafana Ping not sending alerts on JupyterHub downtime

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#160]
![image](https://user-images.githubusercontent.com/22624020/84543127-9b1f5e80-acaf-11ea-8413-e223fc1c9744.png)
Even though JupyterHub was down yesterday, it did not send a Grafana alert. It may have been due to the master node being down, but somehow Grafana site was still up during downtime. 

Looking at the graphs for the last 24 hours, I don't see much any evidence of downtime; although I did add an alert for Endpoint Health since it looks like it shows somewhat of a difference. Hopefully this fixes the issue if this happens later.

![image](https://user-images.githubusercontent.com/22624020/84544816-e6873c00-acb2-11ea-9834-c5e1c98f76ee.png)

**Comment by moorepants** [comment]
We've definitely gotten these alerts in the past for downtime (right?).

**Comment by celine168** [comment]
I don't think we had a period of downtime like this since we reinstated the alerts. I think I fixed it for now (as previously mentioned), but we obviously won't be able to tell until the site goes down again. So I wanted to add this as an issue for now.

**Comment by moorepants** [comment]
Is this fixed? If so, let's close it.

**Comment by rkevin-arch** [comment]
Not sure, but we should have alerts for website downtime. I don't know what the original issue is so I can't tell if it is resolved.

**Comment by rkevin-arch** [comment]
I feel like this is resolved, since 1) we added the grafana alerts to the helm values so they will respawn, and 2) if rooster goes down the cluster could still run normally while losing internet access to send out the alerts. If this happens again we can revisit this.
