### ISSUE TITLE
Error upgrading jupyterhub after adding emails as admin to ~/jupyterhub/config.yaml

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#168]
I've put Kevin and I's email into the config.yaml file under the admins section, and I ran `./upgrade.sh`. It yields an error relating to the jupyterhub chart version; 

`spicy@rooster:~/jupyterhub$ ./upgrade.sh`
`[debug] Created tunnel using local port: '44193'`

`[debug] SERVER: "127.0.0.1:44193"`

`Error: chart "jupyterhub" matching version "0.9-2d435d6" not found in jupyterhub index. (try 'helm repo update'). No chart version found for jupyterhub-0.9-2d435d6`

I suspect this has to do with our recent updating with many of the nodes. The most recent information on that is available [here](https://github.com/LibreTexts/metalc/issues/131#issuecomment-647036760).

**Comment by sandertyu** [comment]
No luck with running the command after `helm repo update` either

`spicy@rooster:~/jupyterhub$ helm repo update`
`Hang tight while we grab the latest from your chart repositories...`
`...Skip local chart repository`
`...Successfully got an update from the "ngshare" chart repository`
`...Successfully got an update from the "jupyterhub" chart repository`
`...Successfully got an update from the "jetstack" chart repository`
`...Successfully got an update from the "stable" chart repository`
`Update Complete.`
`spicy@rooster:~/jupyterhub$ ./upgrade.sh`
`[debug] Created tunnel using local port: '41749'`

`[debug] SERVER: "127.0.0.1:41749"`

`Error: chart "jupyterhub" matching version "0.9-2d435d6" not found in jupyterhub index. (try 'helm repo update'). No chart version found for jupyterhub-0.9-2d435d6`


Running `helm list` it looks like the versions in upgrade.sh and on helm list are the same. 

![helm list](https://user-images.githubusercontent.com/59950537/85210776-a7cb3480-b2f7-11ea-8354-45065140636f.PNG)

**Comment by celine168** [comment]
I think encountered a similar issue once in the past few months for one of the hubs.
The way I fixed it was just changing the version to the latest development release: https://jupyterhub.github.io/helm-chart/#development-releases-jupyterhub

So in this case, try `0.9.0-n107.h7d2d3eb`? You might be able to also get away with the stable release of 0.9.0, but make sure the login, FAQ, and about pages still show up fine (this is why we transitioned to a more recent development release in the first place, so we could customize those pages).

I did a ctrl+f for `0.9-2d435d6` in their helm chart repo page and couldn't find anything. Maybe they changed their naming conventions?

**Comment by rkevin-arch** [comment]
We should upgrade to 0.9.0 (the other versions like `0.9.0-n107.h7d2d3eb` are development versions anyway). Also, isn't the JupyterHub in the jhub namespace in production? We should probably not touch it for now.

**Comment by celine168** [comment]
Are any classes using it right now?
I would usually refrain from changing the versions but summertime might be the best time?

**Comment by sandertyu** [comment]
> Are any classes using it right now?
> I would usually refrain from changing the versions but summertime might be the best time?

Nobody is using the cluster. If the issue is downtime, then it should be fine and we can proceed.

**Comment by moorepants** [comment]
The other thing is that you don't need to add your names there (I think). We already have you as admin's on the hub. We've been adding users to the hub (admin and not) only via the web interface for a long time now.

**Comment by moorepants** [comment]
> Nobody is using the cluster. If the issue is downtime, then it should be fine and we can proceed.

Do not proceed with things that might break stuff. If we want to schedule a downtime, we need to email the users a week or so in advance with a specific downtime.

This upgrade doesn't seem necessary. Let's leave things be if nothing is broken or needs to be fixed. That's a good rule of thumb for production systems.

**Comment by sandertyu** [comment]
Okay, got it. I was confused about how all the permissions worked because I have plenty of access but I am not listed in the config.yaml file. Should I revert the file back to how it was? I added Kevin and I's emails and I also put comments on them noting that `./upgrade` needs to be ran for it to even take effect. 

> We've been adding users to the hub (admin and not) only via the web interface for a long time now.

That makes sense, could I see where all of that information is? It would be useful just to know.

**Comment by moorepants** [comment]
Log into JupyterHub, click "Admin" in the top bar. You can add users there, including admin users.

**Comment by moorepants** [comment]
This probably needs to be added to the onboarding documentation ("request an admin account on the hub") and needs to be in our documentation somewhere "How to add users to the hub".

**Comment by moorepants** [comment]
I noticed that we can't disable admin for Celine and Luigi. I think this is because they are listed as admin in the config file. Can we just have Richard and me listed as admin in the config file and we'll use the jupyterhub interface to give permissions to the others?

**Comment by sandertyu** [comment]
> I noticed that we can't disable admin for Celine and Luigi. I think this is because they are listed as admin in the config file. Can we just have Richard and me listed as admin in the config file and we'll use the jupyterhub interface to give permissions to the others?

Done, only Richard and Jason are listed as admins in the config files and everyone else is added through the interface. Currently the only admins besides you 2 are Kevin and I.

I think this issue can be closed now. The only thing that hasn't been touched on is this down below, which we could maybe make a separate issue for. 

> This probably needs to be added to the onboarding documentation ("request an admin account on the hub") and needs to be in our documentation somewhere "How to add users to the hub".

**Comment by sandertyu** [comment]
Closing this issue, as I've mentioned plans to include documentation about user management elsewhere. I plan to add info about requesting an account to the onboarding document.
