### ISSUE TITLE
Setup user access

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#17]
jupyter.libretexts.org
- Whitelisted ucdavis accounts (need a way for them to request accounts)
  - We want instructors to be able to have accounts and then request accounts for their classes
  - Eventually we will let any ucd credential log in, but for the first academic year we should control this to help us manage and test.
- Anyone with a libretexts account (maybe), we need to discuss with Delmar and Chuck (Tsugi integration, etc)

binder.iibretexs.org
- For now we leave public but don't advertise the service
- Ultimately we need to restrict HTTP requests from only libretexts pages

**Comment by moorepants** [comment]
@Miniland1333 Can you comment on how we might go about setting up shared authentication with Libretexts so that Libretexts user credentials can get them access to the jupyterhub?

**Comment by Miniland1333** [comment]
In production we will likely use SAML 2.0 SSO authentication, but Delmar and Chuck are talking with a group tomorrow over whether the implementation will be Apero CAS or InCommon. If it is InCommon, then  students could use their existing institution credentials that can then plug in to the system. I will attempt to provide more details after tomorrow's meeting.

**Comment by moorepants** [comment]
As far as I understand, accounts for the libretexts wiki are controlled by Delmar, i.e. you have to request an account and then be granted one. Is that true?

If that is true, we'd like to piggy back on that "gate", so that just anyone with a university email can't log into the service. We want exclusive use for "libretexts users" (whatever that might mean). Just some definitions of whom you all will allow to have libretexts accounts can help frame this discussion.

**Comment by moorepants** [comment]
Here is @celine168's discourse question on getting the whitelisting to work: https://discourse.jupyter.org/t/google-oauth-with-whitelist/1751

**Comment by lux12337** [comment]
For now, we will stop working on the whitelisting as some preliminary users check out JupyterHub.

**Comment by lux12337** [comment]
A possible solution for our authentication needs could be to use the GitHub authenticator(people without a GitHub account would have to create one). It supports organization whitelisting and users whitelisting. We have not tested it yet so we are not sure that it will work.

**Comment by Miniland1333** [comment]
I would recommend a Google authenticator if possible since all Ucd members already have an account which you can filter by email address.

-Henry Agnew

**Comment by moorepants** [comment]
Would it be possible for us to allow any ucdavis email to log in and then selectively whitelist gmail addresses as a simpler solution for now? Then we could just ask libretexts users to provide their gmail accounts.

**Comment by celine168** [comment]
Created an issue on the Zero-to-JupyterHub repo: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1345

**Comment by celine168** [comment]
Another suggestion: we can create another JupyterHub in the same cluster with different rules for user access but under a different subdomain or domain path.
At the moment we're still working on getting whitelisting to work with Google OAuth (whether it's with UCD accounts or regular gmail accounts).

**Comment by moorepants** [comment]
> Another suggestion: we can create another JupyterHub in the same cluster with different rules for user access but under a different subdomain or domain path.

I had originally imagined that we'd have jupyter.libretexts.org and jupyter.ucdavis.edu to serve the two user sets. We could do this. Are there any downsides?

**Comment by celine168** [comment]
So it seems like that using OAuth with UC Davis and whitelisting is working! The only caveat is that if a user previously logged into JupyterHub and they are not whitelisted, that user will still be able to log in. If the user has not logged in before and they are not whitelisted, then they will receive a 403 Forbidden Error.

**Comment by moorepants** [comment]
> So it seems like that using OAuth with UC Davis and whitelisting is working! The only caveat is that if a user previously logged into JupyterHub and they are not whitelisted, that user will still be able to log in. If the user has not logged in before and they are not whitelisted, then they will receive a 403 Forbidden Error.

This sounds good. We need to change that 403 page to something that says: Users with UCD kerebos logins should email something@something.edu to request an account. Or something like that.

**Comment by moorepants** [comment]
One downside is that we have to run dual configurations for each hub right? Or we just guarantee that both are the same?

If we do both domains we have the whitelisted ucd working, but we still need a method for libretexts users to login.

Also, Luigi turned off the whitelisting yesterday or the day before because I sent out the general email to a ton of people at UCD telling them to log in. I can send you all those email addresses to add to the whitelist. Or we can turn it off until August 25th.

**Comment by celine168** [comment]
Yes, we can whitelist them if you send the email addresses. They should probably know that it's still a work in progress and we're still messing with stuff.

**Comment by moorepants** [comment]
> They should probably know that it's still a work in progress and we're still messing with stuff.

They do know that, but I want them to at least be able to log in now without issue so they can see that we do have something. We can disable whitelisting for UCD logins for now (until August 20th) and I'd like to figure out a temporary solution to allow Libretext users to log in before August 20th if possible.

**Comment by celine168** [comment]
I believe whitelisting should be disabled.

**Comment by lux12337** [comment]
If we don't restrict the domain('ucdavis.edu') access to JupyterHub, we are able to whitelist both ucdavis emails and gmail emails. We can have a whitelist of both Davis users and LibreTexts users.

**Comment by moorepants** [comment]
That works as a stop gap solution. I'll send a list of emails to white list. Let's go with that.

**Comment by moorepants** [comment]
We have the "email us to get an account" setup. So closing this. Will open new issues for future setups.
