### ISSUE TITLE
Research Prometheus vs. InfluxDB for new cluster

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#171]

**Comment by sandertyu** [comment]
Will do a summary of these and other sources soon;

https://prometheus.io/docs/introduction/comparison/#prometheus-vs-influxdb

https://logz.io/blog/prometheus-influxdb/

**Comment by sandertyu** [comment]
Currently we are using prometheus for the galaxy repo and it works quite well and is easy to setup. I think we can just continue with prometheus and not use InfluxDB.
