### ISSUE TITLE
Research using PostgreSQL database for Z2JH, and if Z2JH hub can have replicas without breaking

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#173]

**Comment by rkevin-arch** [comment]
https://discourse.jupyter.org/t/what-happens-when-the-hub-restarts/1701

**Comment by rkevin-arch** [comment]
Conclusion: probably not worth it. The main reason why we made this issue is that SQLite can't be used if the hub is going to have high availability (aka multiple hubs run at once, so if one fails we can use another as a fallback instantly without downtime). However, the hub isn't written with HA in mind anyway, and there's much more work to do to make it HA than just using postgres. Switching to postgres wouldn't really have any benefits in that department and requires more services to be installed, so we're probably not going to do that.

**Comment by moorepants** [comment]
Thanks Kevin.
