### ISSUE TITLE
Upgrading cluster

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#177]
This is an issue to keep track of the cluster upgrade during the planned downtime from Jul 2nd 2AM up to Jul 3rd 11:59PM (but hopefully won't take as long).

List of things to upgrade:
- [x] All Ubuntu packages on all chicks (incl. chick0, chick1 and chick10. The rest are already upgraded, but still doing an `apt upgrade` anyway) (excluding chick5, still have no idea what happened to it) (also including kubelet (remember to unhold the package!) after upgrading the control plane)
- [x] All Ubuntu packages on rooster (and also helm and kubectl, since both are installed manually rather than through Ubuntu (probably remove that and install using apt))
- [x] All CentOS packages on hen
- [x] k8s control plane from 1.14.3 to 1.18.5 (this is probably the most dangerous part of the upgrade, fingers crossed)
- [x] Helm charts
  - [x] Main JupyterHub 0.9-2d435d6 -> 0.9.0
  - [x] Workshop JupyterHub 0.9.0-n036.hfcf9c2e -> 0.9.0
  - [x] cert-manager 0.8.1 -> 0.15.2 (not technically an upgrade, purged old installation and installed new one, along with new clusterissuer)
  - [x] quickstart nginx-ingress 1.11.0 -> 1.40.2 (uninstalled and reinstalled due to [k8s APIs changing after 1.16](https://stackoverflow.com/questions/58481850/no-matches-for-kind-deployment-in-version-extensions-v1beta1))
  - [x] prometheus-operator 6.7.2 -> 7.5.0 -> 8.15.7 (uninstalled and reinstalled due to the same issue as above)
  - [x] tinseled-penguin node problem detector 1.5.2 -> 1.7.6
  - [x] nfs-client-provisioner 1.2.6 -> 1.2.8
  - [x] ngshare in staging namespace 0.0.1-n256.h95bb74c -> 0.5.1

**Comment by moorepants** [comment]
Ok. Looks good. Connect with @sandertyu as soon as he's back from camping and you all work on this together so both can learn.

**Comment by rkevin-arch** [comment]
Sounds good. I'll also edit this a couple of times (for example, I just added "upgrade packages on hen" to the list) before the actual upgrade, so this isn't final quite yet.

**Comment by rkevin-arch** [comment]
Everything should be finished and ready to go. Feel free to test stuff and let me know if it breaks, and if you think it's good we can send an announcement saying maintenance has ended early.

**Comment by rkevin-arch** [comment]
Forgot about updating this issue. Other than the stuff listed above, during the upgrade we:
- Removed kube-dns from the cluster in favor of CoreDNS used as the DNS solution in the cluster (both were installed for some reason, but we only need one)
- Removed chick5 from cluster, since it's offline (we can readd it later if needed)
- Added an apparmor rule to allow rooster's DHCP server to read its config files that are symlinked from `/home/spicy/metalc-configurations/dhcpd`
- Repopulated Grafana alerts since I accidentally deleted them (also coincidentally fixes https://github.com/LibreTexts/metalc/issues/174), along with adding new alerts for load averages on all nodes and dashboards for visualizing CPU, memory and load average for all nodes in one place (dashboards will be committed to metalc-configurations soon).
The upgrade has finished successfully, so I'm going to go ahead and close this issue.
