### ISSUE TITLE
Chicks 11~18 have low disk storage

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#179]
![image](https://user-images.githubusercontent.com/5837628/87352725-67cf2a00-c510-11ea-984a-a655c599612d.png)
Not an issue for now, but pods scheduled on those nodes might get some out of disk space issues when pulling images.

**Comment by moorepants** [comment]
Some related issues:

- https://github.com/LibreTexts/metalc/issues/116
- https://github.com/LibreTexts/metalc/issues/121

**Comment by moorepants** [comment]
Closing since we have #116 already open.
