### ISSUE TITLE
Setup dockerhub and google credentials for libretexts (instead of Luigi's personal)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#18]

**Comment by lux12337** [comment]
JupyterHub and Binder are now using libretexts accounts. I have stored the credentials for the accounts on rooster.

**Comment by moorepants** [comment]
Can you store the credentials in the private config file repo? (keep all this stuff in the same place)

**Comment by lux12337** [comment]
Ok, I'll add it to the repo

**Comment by lux12337** [comment]
I added the credentials to the repo.
