### ISSUE TITLE
Update our JupyterHub FAQ page

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#182]
The most immediate thing to update in the [FAQ](https://jupyter.libretexts.org/hub/static/external/pages/faq.html) is the process for creating a conda environment on the hub. Currently the page links to some github repositories, but we should just put the information directly on the page. The FAQ is also only available when you are on a JupyterHub webpage; if you are within the JupyterLab interface then you can't directly view our FAQ (at least from my searching). There's a JupyterLab reference and FAQ in the help tab, but those are not maintained by us. It could be nice to add a link to ours here as well I think, if possible. 

![help](https://user-images.githubusercontent.com/59950537/89597446-0b111780-d80f-11ea-9870-cb68497e17ba.PNG)

Jason has also suggested we update the "about" page as well. These static pages are available in the [jupyter-images](https://github.com/LibreTexts/jupyterhub-images) repo.

**Comment by moorepants** [comment]
Yes, I've long wanted a link to the faq in the jupyterlab menu. Good idea!

**Comment by rkevin-arch** [comment]
Looks like we can write a very simple extension to add it in, something like https://github.com/AARNet/jupyterlab-ext-aarnet-help. We would have to publish it to npm though.

**Comment by rkevin-arch** [comment]
How does this look? We haven't updated the FAQ page in a while, but I have added an extension that adds a `LibreTexts JupyterHub FAQ` option in the help menu that opens https://jupyter.libretexts.org/hub/static/external/pages/faq.html.

![image](https://user-images.githubusercontent.com/5837628/89724899-ab0ca380-d9bd-11ea-85ca-64298d3d1aff.png)
![image](https://user-images.githubusercontent.com/5837628/89724901-b233b180-d9bd-11ea-9846-73ad62d1fac1.png)

**Comment by rkevin-arch** [comment]
https://github.com/LibreTexts/labextension-libretexts-faq. Not sure whether we publish this on npm or not (might be the only elagent way to install it without `git clone`)

**Comment by sandertyu** [comment]
We've completed and made this merge. Closing.
