### ISSUE TITLE
Remove the spark environment

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#183]
I'm not sure why but a Spark environment has always been listed on the hub. No one requested this and I'm not sure why it wasn't removed along with the other default environments that jupyterhub lists. Please remove it, as it only adds confusion for users.
![Selection_727](https://user-images.githubusercontent.com/276007/89711309-ca89d900-d989-11ea-831c-ff3c6ac190f0.png)

**Comment by rkevin-arch** [comment]
Should be a simple change. One second.
