### ISSUE TITLE
Add psi4 to the default-env

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#184]
Delmar requested this package:

https://github.com/psi4/psi4numpy

It looks like they have conda packages built for it, but they are not hosted on the conda forge channel.

We should try to find their conda build recipe, then submit the package to https://github.com/conda-forge/staged-recipes. After it is added to conda forge we can add it to our repo2docker conda install list.

**Comment by rkevin-arch** [comment]
Their Github repo says `clone this repository; no install available`, so I'm not sure if this conda package you're talking about is officially supported. Do they need it for a class or just want to install the package for themselves? If it's the latter, maybe cloning it in their home folder and creating a persistent conda environment is the better way to do it.

**Comment by rkevin-arch** [comment]
Searching `psi4numpy` [here](https://anaconda.org/search?q=psi4numpy) yields no results.

**Comment by rkevin-arch** [comment]
Alternatively, is this just requesting us to install the `psi4` package and not `psi4numpy` itself?

**Comment by moorepants** [comment]
If you download this tarball: https://anaconda.org/psi4/psi4/1.4a2.dev923+5de566e/download/linux-64/psi4-1.4a2.dev923+5de566e-py38h4ec3f01_0.tar.bz2

In the info directory there is a meta.yaml and a build.sh. It looks non-trivial, but maybe could be bulit with conda forge.

**Comment by moorepants** [comment]
I guess we need https://github.com/psi4/psi4 too. psi4numpy is what Delmar asked about, but it depends on psi4 for sure.

**Comment by rkevin-arch** [comment]
The tarball you sent is for `psi4` and not `psi4numpy`, and there isn't a package for `psi4numpy`. Will many users be using this package? If not, doing `conda create -n p4env -c psi4 psi4` themselves will create a conda environment in their home directory with psi4, and in general they can install whatever conda packages from whatever channels they like in there and it will be persisted.

**Comment by rkevin-arch** [comment]
That's one of recommended way to do things on the psi4numpy README as well.

**Comment by moorepants** [comment]
Yes, folks can potentially install anything themselves. I don't know if there will be any users. We shoudl assess how much time it would take us to package everything requested for conda forge and reqport back to Delmar on the LIbretexts construction forum. If ti will take too long a time, then we recommend they install on their on. If not, then we can install it for every user.

**Comment by moorepants** [comment]
This is the relevant post on the forum:https://libretexts-constructionforum.groups.io/g/jupyter/message/47

Note that I marked this "medium priority".

**Comment by rkevin-arch** [comment]
They're talking about the "jupyter binder system", so maybe they need it for binderhub because they need ckeditor-binder-plugin to work with it? If so, then we do want to install it into our default image.

**Comment by moorepants** [comment]
Likely, but our goal is to support the same environment in both libretexts pages and the hub.

**Comment by rkevin-arch** [comment]
Yeah, I'm just saying creating their own conda environment is a possible solution if they want to use it in the hub, but not a good solution if they want to use it from binder.

**Comment by sandertyu** [comment]
The Psi4Numpy package is simply not available to install by any means other than by cloning the git repository right now. There doesn't seem to be a clearcut path to putting it on conda-forge (or even making a conda package) at all. We can potentially attempt to build a Psi4 package for conda-forge using the tar you provided, or ask the developers themselves, but Delmar didn't specifically request that so I think we'll have to wait for their response.

**Comment by moorepants** [comment]
Yes, we should not worry with psi4numpy. Users that want to use it should install themselves.

**Comment by moorepants** [comment]
Closing, as users will need to install manually.

**Comment by moorepants** [comment]
Note that the psi4numpy is not a library, people that want to use it should simply use the content. No installation needed. See: https://github.com/psi4/psi4numpy/issues/107

**Comment by moorepants** [comment]
If psi4 is needed, someone needs to create a conda forge feedstock for it or they can run `conda install -c psi4 psi4` themselves in their hub or libretexts page.
