### ISSUE TITLE
Setup the default environment dockerfile

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#19]
We need to choose a base set of software to support. This list of software should ideally be obtained from our (upcoming) users. Maybe we can put together a Google form survey to send to potential users to build this list. Once obtained, we decide what to include, and then setup the dockerfile. We will also need to have some plan for updating those software packages, maybe we do a mass update each 3 months or something.

We should pick a pretty complete and rich environment from the existing ones the Jupyter community has created. The list below has all packages that have been requested from our (upcoming) users that we want to support by default. They will need to be added to whatever default environment we select if not already present.

- [x] matplotlib
- [x] pandas
- [x] scipy
- [x] numpy
- [x] math (not sure what this is, default math module in python?)
- [x] Astropy
- [x] bokeh
- [x] ipython widgets
- [x] bqplot
- [x] nb_conda_kernels
- [x] sympy
- [x] scikit-learn
- [x] statsmodels
- [x] seaborn
- [x] numexpr
- [x] cython (double check on demand compilation works)
- [x] patsy
- [x] requests
- [x] numba (double check JIT compilation works)
- [x] ipywidgets
- [ ] altair
- [x] julia
- [x] octave
- [x] R
- add more to list as we get feedback

**Comment by lux12337** [comment]
All these packages have been installed in the "Default Environemnt" and should be working now.

**Comment by moorepants** [comment]
Cool. I'm going to leave this open because we'll likely be adding lots more as soon as we get some users.

**Comment by moorepants** [comment]
I've opened some issues on the defaul-env repo: https://github.com/LibreTexts/defaul-env/issues
