### ISSUE TITLE
Implement CKEditer plugin for the QUERY system

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#192]
Some quotes from Delmar:

> ok. I have a small request. I really need to duplicate that CKEditor hack to do the same thing (to add code to the HTML).
>
> It is relatively simple:
>
>   1. Add a button on the editor
>   2. When pressed it asked for a single QUERY number (page ID number)
>   3. Then it spits out a specific html code snippet with that number (we provide) into the html (3-4 lines or so)
>
> We can do this in several steps, but faculty need to have their hands held.

And this exchange:

> >
> > Delmar,
> >
> > That sounds potentially simple but I'm not sure I understand.
> >
> > For point 2. does this mean you query at database for this number? Or that the user manually enters a number?
> 
> Manually adding a number.
> 
> 
> >
> > And for 3, you want the results from 2 to generate some html and embed it into the html of the page.
> 
> either. I think your code does the latter.
>
>
> >
> > Is this a one time thing, or you want users to be able to edit this afterwards too?
>
> It is html, so yes.

I'll explain more in the meeting.

(edited by @rkevin-arch: formatting)

**Comment by narrator0** [comment]
Here's the complete spec after communicated with Delmar.

## What is the problem?

Embedding interactive questions on a LibreTexts book is too complicated. Need a CKeditor plugin to ease the process.

## What are the minimum specs?

* User can see a button on CKEditor menu bar with the query site icon
  * Icon can be found [here](https://a.mtstatic.com/@public/production/site_4538/1579208579-favicon.ico)
* A window will show when the button is clicked
* User can input a number (page ID) on the window
* If the user clicks "confirm", the following HTML should be input to the editor:

```html
<div class="box-query">
  <p class="box-legend"><span>Query \(\PageIndex{1}\)</span></p>

  <p class="mt-script-comment">Embed QUERY Assessment</p>
  <pre class="script">template('query', { 'PageID': '#{pageID}' });</pre>
</div>
```

> Replace `#{pageID}` with whatever number input by the user on the previous step.

* User can edit the content when comes back to the edit page

## What do we need to accomplish this?

* Register a new CKeditor plugin with `CKEDITOR.plugins.add`
* Register a new CKeditor dialog window with `CKEDITOR.dialog.add` with the following content:
  * A text input with validation to make sure it is a number
* Register a new CKeditor UI button with `editor.ui.addButton` (`editor` is the editor instance)

## Extra nice to have features

* Track how many blocks there are on the same page and automatically increment `\(\PageIndex{1}\)`

**Comment by narrator0** [comment]
Repo created https://github.com/LibreTexts/ckeditor-query-plugin.
