### ISSUE TITLE
Add software licenses to our repositories

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#194]
We agreed to add MIT licenses to our repos if there are no conflicts (like GPL was with the CKEditor).

- [x] protogalaxy
- [x] default-env
- [x] metalc
- [x] jupyterhub-templates (?)
- add others to this list

**Comment by celine168** [comment]
Although it seems that [most (if not all) official puppetlabs modules have an Apache 2.0 license](https://github.com/puppetlabs/), I haven't yet found any information anywhere whether we needed to choose that license for ours.

**Comment by moorepants** [comment]
I'm fine if we want to choose Apache 2.0 for the puppetlabs module. Apache isn't like GPL though, so we can choose any license for our files.

**Comment by sandertyu** [comment]
Looks like this issue can be closed, all the repos have had licenses added
