### ISSUE TITLE
Use Google Analytics to track pageviews on the hub

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#196]
Delmar is setting this up:  https://chem.libretexts.org/Sandboxes/admin/1.20%3A_ToDo/Library_Analytics and wants to know if we can add GA to the hub. Let's investigate. I think we'd really only want to track landings on the login page.

**Comment by moorepants** [comment]
We could, at the minimum at the GA code to the login, about, faq pages.

**Comment by TimStewartJ** [comment]
This is done and ready for merging if it's something we're still interested in.

**Comment by TimStewartJ** [comment]
This is active on production jupyterhub now.
