### ISSUE TITLE
Migrate away from the "stable" helm repo

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#199]
The stable helm repo is being deprecated (it's actually been going on for almost an year, I just didn't notice it). See [their deprecation timeline](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline). Most notably, the `kubernetes-charts.storage.googleapis.com` will be deleted on Nov. 13th. We need to migrate everything outside of it ASAP.

Current helm charts on flock that still uses this repo:
- [ ] nfs-client-provisioner (see https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/15, may need to find a new solution for nfs or maintain our own helm chart temporarily?)
- [ ] node-problem-detector (no replacement yet, but are we even using this at the moment?)
- [ ] prometheus-operator (replaced by prometheus-community/kube-prometheus-stack, this is currently in effect on galaxy, but we need to port over our config.yaml for the new chart)

Current helm charts on galaxy that still uses this repo:
- [ ] nfs-client-provisioner (same as above)

We need to figure out a solution for nfs-client-provisioner (especially since it's so important for all PVCs to function), and we need to worry about how to migrate over prometheus (we will lose monitoring in the meantime so we should be careful).

**Comment by moorepants** [comment]
That's a pain. I suppose this is the priority this week.

**Comment by rkevin-arch** [comment]
I've downloaded the helm charts locally (it's also on rooster in my own folder) so we would be able to change our configs and `helm upgrade` at least. I guess this is no longer a super high priority, although this should probably be done during winter break or some other planned downtime (since changing nfs-client-provisioner is probably not safe when the cluster is in operation).

**Comment by celine168** [comment]
I'm still a bit rusty on charts so please bear with me...

If we do need to host the chart somewhere, is [Artifact Hub](https://artifacthub.io/) an option?
I haven't found any other NFS dynamic persistent volume provisioners yet while researching.

**Comment by rkevin-arch** [comment]
We probably don't need to host the charts. I've downloaded them locally (see `~/rkevin/*.tgz` on rooster) and helm can install local charts. We do want to migrate away but there is no hard deadline anymore.

**Comment by sandertyu** [comment]
We've migrated nfs-client-provisioner, so this is good to close.
