### ISSUE TITLE
Handling packages unabled to be installed via repo2docker

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#201]
Based on the issue raised in https://libretexts-constructionforum.groups.io/g/jupyter/topic/75068383, where a writer requested Octave 5.2 on our default environment for a LibreTexts textbook.

Octave 5.2 is only available via apt on [Ubuntu 20.04](https://packages.ubuntu.com/focal/octave) and not on [Ubuntu 18.04](https://packages.ubuntu.com/bionic/octave). Repo2docker currently uses Ubuntu 18.04, although there are talks to eventually move to 20.04 or give the option for users to specify so ([draft PR](https://github.com/jupyterhub/repo2docker/pull/909) and [related issue](https://github.com/jupyterhub/repo2docker/issues/487)).

I'm creating this issue to discuss how we should handle this case and cases like these in the future, where repo2docker may not give the features/packages that LibreTexts users may want. If this issue becomes common, we may want to prioritize https://github.com/LibreTexts/metalc/issues/85 and allow users to create their own repo2docker/Dockerfiles as environments.

**Comment by moorepants** [comment]
I think we should stick to supporting only the packages available in 18.04 APT or via conda (conda-forge channel). We have a couple special cases: sage, julia right now, but those will eventually work smoothly from conda installs. Octave can also be installed via conda but last time I tried it didn't work.

**Comment by moorepants** [comment]
And yes, I see #85 as the solution for users that need something we don't support. For this Octave 5.2 issue though, solving #85 is a lot of work for adding one function to the user space.

**Comment by moorepants** [comment]
We determined that repo2docker is staying on 18.04 for now, so we will have to stick to those APT packages. If conda-forge's octave package is updated (or we update it), then we could use that.

**Comment by sandertyu** [comment]
Octave is [available through conda-forge](https://anaconda.org/conda-forge/octave) but it is on an older version than what we install through apt. Additionally, most of the octave packages are not available through conda-forge, so we would have to find some other way to install them. For now, it is probably best to stick with apt.

**Comment by moorepants** [comment]
We stick to what we can install with repo2docker. Users can install manually otherwise. Closing.
