### ISSUE TITLE
Selecting hardware for galaxy cluster

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#203]
This is discussion on selecting hardware for the galaxy cluster.

## Proposed requirements
* @rfeltstykket suggests 2U servers. 
* 128 - 256 GB RAM, 2 CPU sockets.
* 3 master nodes (could be used by the current 1U servers)
* 4-5 worker nodes 
* 4 hard drive bays preferred
* Prefer configured > not since we cannot build over winter break

We currently have:
* 18 servers in total, including flock
  * 16 GB - 64 GB RAM
  * 6 core CPU

## Found prices
* 2U servers, barebone: https://www.newegg.com/p/pl?N=100283189%20600009047%20600009050%20600009053%20600009066%20600009067%20600315549%20600355181%20600416503%20600473523%20601330649%204814%20600012597&cm_sp=Cat_Server-Workstation_2-_-VisNav-_-2U_5 ($1000-1500)

## Current usage by users
Current limits/guarantees:
|  | JupyterHub | BinderHub |
| - | - | - |
| CPU guarantee / limit | 0.5 / 4 | 0.5 / 4 |
| Memory guarantee / limit | 7G / 7G | 2G / 2G |

The highest memory usage that I've seen users use (very anecdotally) is around 1000 MB. Grafana doesn't let me go further back than an hour on this table for some reason, but here is an idea:
![image](https://user-images.githubusercontent.com/22624020/100051997-dd59d980-2dd1-11eb-8dfc-f4009e40570b.png)

## Other info
Some information about servers in other clusters:
* [UC Berkeley Stats Cluster](https://statistics.berkeley.edu/computing/servers/cluster)
* [Buffalo](http://www.buffalo.edu/ccr/support/research_facilities/general_compute/cluster-hardware-specs.html#front-end)

**Comment by celine168** [comment]
Meeting notes (12/1): Richard and Tom will handle this task.

**Comment by sandertyu** [comment]
Closing since this is out of our hands now.
