### ISSUE TITLE
Kubernetes 1.20.0 breaks nfs-client-provisioner

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#209]
See https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25.

**Comment by rkevin-arch** [comment]
Temporary fix: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/26#issuecomment-743745469. It works for now, but I'm keeping this issue open until that PR is merged upstream and we can switch to an official image.

**Comment by rkevin-arch** [comment]
The nfs-client-provisioner (now called nfs-subdir-external-provisioner) has made an official release (see kubernetes-sigs/nfs-subdir-external-provisioner#49). We should switch our helm chart to this, which would be properly maintained.

**Comment by sandertyu** [comment]
We should switch to this at about the same time we do the cluster upgrade.

**Comment by sandertyu** [comment]
We can probably use the readme on this page [here](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner). It shouldnt cause any problems to migrate as far as I know. I've asked kevin about whether we should remove the old provisioner first or what.

**Comment by sandertyu** [comment]
We've updated to the new nfs provisioner with no issues.  Starting a pod on jhub gives all the correct data, so I assume it is working properly. Before installation, we deleted the nfs image installed not through helm with `kubectl delete deployment nfs-client-provisioner` and `kubectl delete storageclasses.storage.k8s.io nfs-client`.
