### ISSUE TITLE
Use binder-built docker repo for JupyterHub rather than retagging

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#214]
#showerthoughts: If we ditch the default-env and default-test repos and just use the repo2docker one for literally everything (including staging/prod hubs), we won't have the weird retagging thing to worry about anymore, and it would make the process a lot more streamlined. Downside is people can't look at the docker image:tag and immediately tell which default-env version it corresponds with, but you can add a comment in the helm values. Not sure if this is a good idea or not.

**Comment by sandertyu** [comment]
This is current policy, but the documentation in default-env needs to be updated to reflect it. The README is currently very long and confusing because it includes multiple build methods. We should shorten it down to just the best method (using curl and not retagging).

**Comment by sandertyu** [comment]
Documentation on staging has been updated to reflect this.
