### ISSUE TITLE
Create some examples of installing custom software in the libretexts construction guide

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#215]
Our current policy is that we will install packages system-wide for users if they are available in the standard Ubuntu 18.04 APT repos or in the conda forge channel for conda packages (see the FAQ: https://jupyter.libretexts.org/hub/faq#how-can-i-install-custom-packages). We need one or more pages in the Libretexts construction guide that explain this policy (note that libretexts users may never visit the jupyterhub faq). The pages should also give a couple of examples: installing a package from a different conda channel, or one from conda forge that we don't already have installed, maybe a python package from pip, and/or downloading a tarball and compiling it from source. These pages should also clearly state that installing custom packages is an **unsupported feature** and that users are on their own when trying to do this.

The use case we want to give a bit of help on can been seen here with @Miniland1333's attempt at installing a difficult package:
https://github.com/LibreTexts/ckeditor-binder-plugin/pull/137

Construction guide: https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)

**Comment by celine168** [comment]
Another option could be to allow LibreTexts users to create and specify GitHub links to their own repo2docker repositories by forking either default-env or any of the available [binder-examples](https://github.com/binder-examples/).

**Comment by moorepants** [comment]
Yes, that's what this issue is about: https://github.com/LibreTexts/metalc/issues/85

**Comment by TimStewartJ** [comment]
I've started documentation of installing custom packages: https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Installing_custom_packages

**Comment by moorepants** [comment]
Looks good! Two thoughts:

- I would use conda on that page not mamba. mamba is a brand new tool that is getting more use. But I think it will confuse people more than not, especially if something doesn't work as expected or it isn't compaitlbe with conda in some way.
- I don't think psi4 is a good example to use to introduce because you have to use a very atypical conda channel call and it has some very strict dependencies that are super hard to solve properly. My recommendation for installing psi4 is to create a conda environment first, then install only it in the environment using conda. But this cannont yet be done on libretext, so pick another package that easily installs with conda.

**Comment by rkevin-arch** [comment]
> I would use conda on that page not mamba

Conda takes literal hours to solve, so I think mamba is a much better option. For the most part, I think conda and mamba are fairly interchangable.

> My recommendation for installing psi4 is to create a conda environment first, then install only it in the environment using conda

This causes some problems, since the spawned kernel would be in the old conda environment, so it probably won't have access to the newly installed package. I'm not sure how to switch a currently running kernel to a different conda environment (or if that's even possible). Alternatively, we can kill the kernel and spawn a new one in the new environment (while keeping the pod), but it will probably require a lot of hacks in Thebe to get it to work. Overall I don't think this is a great option.

**Comment by moorepants** [comment]
> Conda takes literal hours to solve, so I think mamba is a much better option. For the most part, I think conda and mamba are fairly interchangeable.

I understand that, but that's mostly due to psi4 having odd constraints in this case. I manage an environment with twice the packages in default-env on my personal computer and conda handles it fine in just a few minutes.

For the conda environment, this only works on jupyterhub, not on libretexts pages. That's why I brought up this: https://github.com/LibreTexts/metalc/issues/85#issuecomment-757445554

**Comment by moorepants** [comment]
> For the most part, I think conda and mamba are fairly interchangable.

This may be the case, but there is a decade of documentation across thousands of packages that tell everyone to `conda install`. I'm not interested in becoming a support team for libretexts users trying to use mamba.

**Comment by rkevin-arch** [comment]
> I manage an environment with twice the packages in default-env on my personal computer and conda handles it fine in just a minute.

FWIW, if I remember correctly our default-env took at least 15 minutes to solve (not to install the packages, just to solve) before repo2docker switched to mamba. That's a really long period of time for there to be no output from the code cell, and I think most people will assume the code cell is dead.

> For the conda environment, this only works on jupyterhub, not on libretexts pages.

Ah OK, since this issue is about the construction guide I assume this is aimed at libretexts page authors.

> This may be the case, but there is a decade of documentation across thousands of packages that tell everyone to conda install. I'm not interested in becoming a support team for libretexts users trying to use mamba.

I think a small message saying "mamba is like conda, but faster" on the page should suffice, but I totally understand some authors may come looking for you with mamba-related questions.

**Comment by moorepants** [comment]
> I think a small message saying "mamba is like conda, but faster" on the page should suffice, but I totally understand some authors may come looking for you with mamba-related questions.

Fine with that. We can mention mamba is available, but I think our docs should stick to conda until mamba is mature. I personally hope the conda and mamba people have some kind of plan to integrate the two or deprecate conda. I don't know. It isn't clear what is going to happen there. This past year we are seeing quite a few of the top projects switching to mamba for various things. mamba is 2 years old. conda is 9 years old. I think patience is best when adopting the new tech, otherwise there is lots of extra work for us.

**Comment by TimStewartJ** [comment]
Alright, I've implemented the changes requested into the page. Let me know if anything should be changed. Also, if there are any specific packages that may serve as better examples, let me know of them as well.

**Comment by moorepants** [comment]
To close this out make it consistent to call the bash commands in the construction guide across all kernels.
