### ISSUE TITLE
LibreTexts Status Page alerts

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#216]
We have a nice [status page](https://status.libretexts.org/) for our LibreTexts services, but the alerts are not functioning properly. I'm trying to subscribe with our email right now, and the captcha is telling me "rate limited or network error" as well. Seeing this in console;

![console-errors](https://cdn.discordapp.com/attachments/763198235237154837/798770360190763048/unknown.png)

**Comment by moorepants** [comment]
@Miniland1333 Is this something you can help with?

**Comment by Miniland1333** [comment]
Okay we think we have the initial subscription handled. Now we just have to test for Jupyter that the manual and automatic alerts are sending.

**Comment by sandertyu** [comment]
Statuspal is operational and we have received emails from it. closing
