### ISSUE TITLE
Invalidate Cloudflare cache upon push to production for ckeditor-binder-plugin

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/metalc#218]
Currently we have a Cloudflare cache with a 2 hour TTL for ckeditor-binder-plugin. Therefore, pushes to production can take a while to show up. This makes testing a page on production more difficult (when we want to verify a page in production works outside of query/staging), and it means if we fix a bug it isn't rolled out to users immediately. Cloudflare has [APIs](https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare#h_fb40387b-d068-4c38-96fc-29d05d35e81e) to invalidate the cache, so our update can go through immediately. @Miniland1333 Do you mind setting this up in the [GitHub action](https://github.com/LibreTexts/ckeditor-binder-plugin/blob/staging/.github/workflows/main.yml)? Only you have the Cloudflare credentials.

**Comment by Miniland1333** [comment]
Got it working with my main repository with https://github.com/LibreTexts/Libretext/pull/119. 

Attempting to address this with:

1. https://github.com/LibreTexts/ckeditor-binder-plugin/pull/143
2. https://github.com/LibreTexts/ckeditor-query-plugin/pull/7

**Comment by moorepants** [comment]
@LibreTexts/jupyter-team can one of you review @Miniland1333's PRs? Thanks.

**Comment by TimStewartJ** [comment]
This was fixed in the two PR's earlier, closing.

**Comment by Miniland1333** [comment]
Closed by https://github.com/LibreTexts/ckeditor-binder-plugin/pull/143
