### ISSUE TITLE
Set JupyterHub GUI upload limit to a suitable number

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#219]
Max Rudolph is trying to upload files that are 100 mb or ever bigger than 100 mb via the gui. We had the limit set to a small number (?10mb?), but @rkevin-arch bumped it to 100mb. What should we set this number to? And how should we inform the user that they can use something like wget or curl to upload larger files. We should also inform then of the max size we give each user. Maybe this all just needs an entry in the FAQ.

**Comment by sandertyu** [comment]
I think an FAQ entry is the best way to go. Can probably go in the "for instructors" section. I'll start it tonight.

**Comment by moorepants** [comment]
Maybe let one of the new folks add this one, since you know how to do it.

**Comment by rkevin-arch** [comment]
The limit is imposed by the ingress, and can actually be disabled altogether by setting it to 0. I've just done that and is currently uploading a 700+MB test file to verify it works.

**Comment by rkevin-arch** [comment]
Confirmed this issue is fixed.
Some further reading for the interested:
https://github.com/jupyterlab/jupyterlab/issues/4214
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
https://github.com/kubernetes/ingress-nginx/blob/1c908029eee0aa07b5740a6d380e5034291528b0/charts/ingress-nginx/values.yaml#L31

**Comment by sandertyu** [comment]
Gonna reopen till the FAQ is finished being written. I've made changes to the [staging branch of jupyterhub-templates](https://github.com/LibreTexts/jupyterhub-templates/tree/staging) and they are viewable on the [staging-hub](https://staging.jupyter.libretexts.org/hub/faq). Just a brief suggested outline if someone else wanted to finish.

**Comment by rkevin-arch** [comment]
There's no upload limit anymore, so I don't think we need an FAQ, but that's my opinion.

**Comment by sandertyu** [comment]
> There's no upload limit anymore, so I don't think we need an FAQ, but that's my opinion.

Yeah it should be clear but detailing that they can also use terminal commands if they need to access remote files which are not on Github would be good to inform users I think.

**Comment by sandertyu** [comment]
Upload limit is gone and uploading files is mentioned in the FAQ
