### ISSUE TITLE
Evaluate and decide on jupyter - libretexts page integration software

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#22]
This is taken from a prior issue (now closed) at: https://github.com/LibreTexts/Tech-Issues/issues/4

Add more to this list as discovered.

- Juniper seems to do what thebelab does but was inspired by thebelab: https://github.com/ines/juniper
- A tool to create interactive books with Jupyter and markdown files: https://github.com/choldgraf/jupyter-book
- thebelab (what we are already using): https://github.com/minrk/thebelab
- nbinteract https://www.nbinteract.com/ (I think this is what berkeley data8 is using)
- Berkeley's Data8 course http://data8.org/ (uses interactive pages I think)
- Our book on Teaching and Learning with Jupyter: https://jupyter4edu.github.io/jupyter-edu-book/
- I'm pretty sure that the SAGE team under the OpenDreamKit grant is working on this, we shoudl figure out what they are doing.

Summary document of the survey results: https://docs.google.com/document/d/1eV08l_4djKJ7bc8r0LPbD5bp3QT7mHTZgABUleH15H0/edit?usp=sharing

Task list

- [x] Create a document that summarizes the survey results

**Comment by lux12337** [comment]
From a simple test that I ran on the [example Juniper website](https://ines.github.io/juniper/) by declaring a variable in one block and trying to print it in another block, it seems like the code cells are independent from each other, so it might be a good option to test out instead of thebelab?

**Comment by moorepants** [comment]
We need to do some research to find out what exactly we even want this system to do. There currently isn't a user story that would guide whether we want cells independent or not within a single libretexts page. A basic survey and interviews with some of the potential libretexts uers would be helpful here to figure this all out.

**Comment by celine168** [comment]
@moorepants @lux12337 Any suggestions on what to add to the survey? https://forms.gle/Z2SYkxm4bRWCWcKT6

**Comment by celine168** [comment]
I've finished editing the survey and will be sending it to the LibreTexts groups.io soon. Let me know if you wish to change anything (although I do think I gave both of you full editing permissions).

**Comment by moorepants** [comment]
LGTM!

**Comment by moorepants** [comment]
One small comment, maybe link directly to this page: https://jupyter.org/jupyter-book/features/notebooks.html and tell them to press the "thebelab" button at the top.

**Comment by celine168** [comment]
I like that page! I added it in.

**Comment by celine168** [comment]
Sent out the survey to [groups.io](https://libretexts-constructionforum.groups.io/g/main/message/176) and emailed Dorte (with a CC to Delmar).

**Comment by celine168** [comment]
Compiled results here: https://docs.google.com/document/d/1eV08l_4djKJ7bc8r0LPbD5bp3QT7mHTZgABUleH15H0/edit#

**Comment by moorepants** [comment]
I'm closing this in favor of the various other issues we've broken this problem into. #86 is most like this one.
