### ISSUE TITLE
Upgrade Jupyterhub Helm Chart from 0.10.6 -> 0.11.1

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#225]
A new Helm chart for JupyterHub that we use to install Jupyterhub on Kubernetes is available, but after the upgrade our [About](https://staging.jupyter.libretexts.org/hub/about) and [FAQ](https://staging.jupyter.libretexts.org/hub/faq) HTML pages no longer load properly. We supposedly add these HTML pages to the hub via the `extraConfig.templates` section of the `config.yaml` seen [here](https://github.com/LibreTexts/galaxy-control-repo/blob/1911c7e0a9cef88ae2cb6c5cc1fd42d2155dce1f/kubernetes/staging-jhub/config.yaml#L99). 

I had to make changes to the authentication syntax as well as the `pdb` proxy name in order to make our `config.yaml` compatible with 0.11.1. You can read more about those changes here in their [CHANGELOG](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md). Additionally, this new helm chart moves from jupyterhub [1.2.2 to 1.3](https://github.com/jupyterhub/jupyterhub/compare/1.2.2...1.3.0) which introduces some `async` changes to the `render_template` function we use in the `extraConfig.template` section. 

At the moment, I suspect either something is wrong with the `extraConfig.template` code or changes to the proxy are messing things up.

**Comment by sandertyu** [comment]
This is fixed and available on production, the solution was to add `async` before each function in the `templates` section and `await` before the first parameter of that function.

**Comment by moorepants** [comment]
Why don't we see any pull requests with changes like these?

**Comment by moorepants** [comment]
Also, for changes like this, we need to be able to have people test things on staging first. It isn't clear that a proper review and check process is happening before things are pushed to production.

**Comment by sandertyu** [comment]
The changes were made to `galaxy-control-repo/kubernetes/staging-jhub/config.yaml` and other such files. We haven't been making PR's because either we are changing Puppet code and the only way to test it is to deploy it via the `production` branch, or the changes are to the `kubernetes/` folder and the contents on github have no effect on the status of the cluster. The helm charts are manually installed on `gravity` using the config files in the control-repo.

All of the changes made for this fix were tested on staging first and then deployed to production jhub today because there are no users on it. I'm working with Kevin at the moment and nothing was deployed to production jhub till now.

**Comment by moorepants** [comment]
Overall, the use of the github PR+review seems to have declined from my perspective. You all may be communicating and checking each other's work but it is not apparent to me. I'd like to see the workflows angle back towards the process we used to have. I'll bring it up at the meeting.
