### ISSUE TITLE
Request for matplotlib, bokeh, and ipywidgets

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#23]
Taken from: https://github.com/LibreTexts/Tech-Issues/issues/6

From an email:

> ... a Ph.D. student in our department at MIT, has been
> working on interactive visualizations to illustrate some of the
> concepts in the "Geophysical flows" LibreText book. He had a few
> questions:
>
> 1. Is there a development environment on LibreText where we can
> prototype the visualizations to make sure they'll work on LibreText?
>
> 2. Would it be possible to get access to matplotlib and the Bokeh
> plotting library on LibreTexts? Matplotlib would be great as it's a
> very mature and feature-rich library and it plays well with IPython
> widgets for interactivity. Bokeh would help for advanced
> visualization, e.g., of particle transport in a geophysical flow. It
> seems that right now we can only use bqplot which cannot make the
> kinds of plots needed for visualizing geophysical flows, such as
> vector fields, stream plots, and 3D surfaces.

My email response was that it is coming and that this will definitely work.

- [ ] Let these people know about the environment.

**Comment by celine168** [comment]
I created a "Geophysical Environment" using repo2docker from [this repository](https://github.com/LibreTexts/geophysical-env). It should have those 3 packages by default when you start the environment.

**Comment by moorepants** [comment]
closing in favor of #28
