### ISSUE TITLE
Rename titles in construction guide to follow the numbering

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#230]
The prior construction guide pages used numbering in the titles. Looks like most new pages don't. This should be made consistent:
![image](https://user-images.githubusercontent.com/276007/109474356-b700a580-7a74-11eb-8df9-f1ceb5d65da5.png)

**Comment by moorepants** [comment]
I also don't see the ipyvolume page listed there: https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipyvolume_for_3D_plotting

All pages should be in that table of contents listing and have consistent names.

**Comment by mandeepika** [comment]
[Updated it](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements).

**Comment by moorepants** [comment]
Nice!
