### ISSUE TITLE
Query Textbook pages for each kernel

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#234]
it would be nice to have pages on Query with each kernel in our default-env already prepared so that we can quickly test it when deploying CKEditor Binder Plugin. The code doesn't need to be super complicated, we just need to verify that each kernel works

**Comment by moorepants** [comment]
These can be copied over from the construction guide as a quick solution.

**Comment by sandertyu** [comment]
I've made a category for each non-python kernel [here](https://query.libretexts.org/Sandboxes/jupyterteam@ucdavis.edu/Kernels_for_testing_CKEditor-Binder-Plugin). You can view the different pages by going to "contents" and then opening the "kernels for testing ckeditor binder plugin" folder";

![kernel-pages](https://cdn.discordapp.com/attachments/763198235237154837/849890357734932510/unknown.png)

python is available by going to the top level jupyterteam@ucdavis.edu sandbox

**Comment by moorepants** [comment]
Great!
