### ISSUE TITLE
Setup and support grading software

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#24]
- nbgrader
  - Jason uses in his class and others are likely to also
  - May only work with the old notebook file browser (not jupyter lab)
  - Needs some tweaks to handle multiple classes (at least on the old single server setup)
- okpy
  - Chris and Seth are interested in this.
  - Not sure how it intergrates with Jupyter
  - Used in berkeley's data8
  - Might be a separate service we'd need to run?

Task list

- [ ] Add FAQ question about grading notebooks, point them to okpy and explain nbgrader doesn't work

**Comment by moorepants** [comment]
Couple other notes:

- Seems like berkely uses okpy, but there is this simpler tool that is related: https://github.com/data-8/Gofer-Grader
- Here is a simple tool for designing notebooks with hidden solution blocks: https://github.com/rmotr/jupyterlab-solutions

**Comment by celine168** [comment]
nbgrader doesn't seem to work with JupyterLab, at least not without a few hacks: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/174#issuecomment-410235452

It seems like an intensive workaround to get it to work.

**Comment by moorepants** [comment]
Sounds like OKPy is a working solution and the only downside is that users have to go to a different website, i.e. okpy is not integrated into jupyterhub like nbgrader. @celine168 Said she'd email the okpy people to get clarity on the free usage of the service and see if all the ucd/libretexts classes can use it regardless of type. Jason will check it out and try to use it in his fall course as a test run.

**Comment by celine168** [comment]
Emailed them.

**Comment by celine168** [comment]
Emailed for the third time.

**Comment by moorepants** [comment]
Don't worry about it anymore. We can recommend it to any user that needs it and if okpy tells them no, we can deal with it after that.

**Comment by moorepants** [comment]
Let's see what the survey tells us about grading needs and then decide whether we want to figure out ngrader.

**Comment by moorepants** [comment]
This issue can be closed once the FAQ is updated to include the okpy recommendation and why nbgrader is not currently available.

**Comment by moorepants** [comment]
FYI, we have submitted a project to the CS senior design on getting nbgrader working with jupyterhub on containers.

**Comment by moorepants** [comment]
Here is the repo for the new project by the seniors: https://github.com/lxylxy123456/ngshare

**Comment by moorepants** [comment]
This is also a piece of software that may do something similar to ngshare: https://github.com/edina/nbexchange

**Comment by moorepants** [comment]
I just saw this announcement too: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter-education/A8NbwZ0IxUA/u0dFfSC1CAAJ

Otter-grader: https://otter-grader.readthedocs.io/en/beta/

**Comment by moorepants** [comment]
We have ngshare setup and running on staging. We really need some pilot users for this as a next step. I'm not sure that will happen till fall.

**Comment by moorepants** [comment]
Do we have ngshare running on production yet? If so, close this.

**Comment by rkevin-arch** [comment]
Not yet, I thought we're waiting for users to test ngshare on staging first

**Comment by moorepants** [comment]
No users are going to test it unless we actively go out and get them. So that didn't happen this summer. Let's just run it on production. Maybe there will be some people that want to use it this fall.

**Comment by moorepants** [comment]
ngshare is running on production, so closing.
