### ISSUE TITLE
Binderhub docker registery healthcheck failing

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/metalc#241]
At https://binder.libretexts.org/health you can see that there is a `{"service": "Docker registry", "ok": true}` field, and it has been alternating between true and false for a few hours now. The registry is specified in the `config.yaml` file for binderhub in the control repo. Further logs can be seen with `kubectl describe pod -n binderhub hub-<name>` and `kubectl logs -n binderhub hub-<name>`.

While most of our services seem unaffected by this, if you try to build an image directly through binder.libretexts.org that should be cached, it will try and rebuild it. jupyter.libretexts.org is able to properly access the default-env 3.1.0 image, but if you try to build it on binder, it will believe that the image does not currently exist, and build again. This seems mostly to not effect libretexts.org, but Tim said they noticed it was causing issues for a bit.

If the [registry](https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/setup-binderhub.html#id2) is failing and it's being hosted externally (pretty sure it is currently), I'm guessing that this may not be something under our control. Alternatively, we could try and set up our own registry as has been suggested before, which has other benefits as well.

**Comment by rkevin-arch** [comment]
@moorepants FYI this is what has been triggering all the tablesetter and statuspal alerts for the past day.

**Comment by TimStewartJ** [comment]
It looks like upgrading to the newest helm chart for binderhub should fix this issue (0.2.0-n636, as seen [here](https://github.com/jupyterhub/binderhub/compare/e777436...8e3b5ac)). Unfortunately, trying to upgrade to this version throws this error on gravity: `Additional property etcJupyter is not allowed`. I'm currently looking through the changes to see if there's anything we need to change in our config.yaml to fix this. The second most recent version still works with our cluster but does not include the registry fix.

**Comment by sandertyu** [comment]
We've looked around and not been able to find any obvious breaking changes. The [jupyterhub changelog](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/CHANGELOG.md) goes into more detail about a new helm chart validation schema, which is related to the issue that we are seeing which is exactly;

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
binderhub:                                                                                                                                         
 - (root): Additional property etcJupyter is not allowed
 ```
 
 However, mybinder.org is also using this [etcJupyter](https://github.com/jupyterhub/mybinder.org-deploy/blob/1f0cd534fe30b1e708d8a5b7232ac211c77358b0/mybinder/values.yaml#L5) section and seems to be having no problems running the [latest helm chart](https://github.com/jupyterhub/mybinder.org-deploy/blob/1f0cd534fe30b1e708d8a5b7232ac211c77358b0/mybinder/Chart.yaml#L47). For now, I've asked about it on on [gitter](https://gitter.im/jupyterhub/binder).

**Comment by TimStewartJ** [comment]
Response on gitter: 

![image](https://user-images.githubusercontent.com/37033036/126675355-7a946efd-5ef0-4feb-ae07-ce10b0730f56.png)

It looks like we'll just have to follow along with what they said? It makes me wonder how long etcJupyter hasn't been in use for and if that particular configuration has even been working on our cluster this whole time.

**Comment by TimStewartJ** [comment]
Here's some references to what they were talking about:
https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1990
It seems like a realtively easy thing to configure so I reckon we should be able to do this shortly

**Comment by sandertyu** [comment]
We've updated to the latest helm chart so we suspect that this issue will be fixed. If we continue to get alerts about the health endpoint, we can create a new issue and find the other source.

**Comment by moorepants** [comment]
> reckon

Where are you from Tim? That's what we say where I grew up! I never heard in in CA.

**Comment by sandertyu** [comment]
I believe this issue is still persisting. The docker registry shown at the health endpoint is flipping between okay and not okay, causing statuspal alerts. I'd like to figure out the exact url that [health.py](https://github.com/jupyterhub/binderhub/blob/e2ebb7a948bc8e120d9b1ec422ec25b048d5831a/binderhub/health.py#L147) is checking, that way we can verify it for ourselves. Some of the code used here can be found in [registry.py](https://github.com/jupyterhub/binderhub/blob/master/binderhub/registry.py#L14) and there is a test for it [here](https://github.com/jupyterhub/binderhub/blob/master/binderhub/tests/test_registry.py), but both of these items have failed their own automated tests.

The main issue here is that binder will continue to rebuild default-env on libretexts even though it has been built and pushed before; it is unable to consistently access the dockerhub registry.

**Comment by TimStewartJ** [comment]
> Where are you from Tim? That's what we say where I grew up! I never heard in in CA.

Ah, sometimes my friends and I speak in silly accents and it looks like its spilled over onto my github speak as well.

Anyway, it seems I've reckon'd wrong. If its any sort of help, it seems you can see the new URL's here under the registry section: https://status.docker.com/.

Maybe something went wrong with the application of the new updates on our end? We'll probably have to find a way to see if our binderhub is actually checking the right registry URL or not.

**Comment by rkevin-arch** [comment]
It looks like this issue might be caused by me, sorry about that. Here's a snippet from `kubectl logs -n binderhub binder-6dcf584b7-wqvb5`:
```
[I 210723 06:34:10 health:149] Checking registry status
[I 210723 06:34:29 health:149] Checking registry status
[E 210723 06:34:30 health:51] Error checking check_docker_registry
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/binderhub/health.py", line 49, in wrapper
        res = await f(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/binderhub/health.py", line 79, in wrapper
        last_result = await outstanding
      File "/usr/local/lib/python3.8/site-packages/binderhub/health.py", line 27, in wrapper
        return await f(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/binderhub/health.py", line 154, in check_docker_registry
        await registry.get_image_manifest(
      File "/usr/local/lib/python3.8/site-packages/binderhub/registry.py", line 220, in get_image_manifest
        resp = await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 429: Too Many Requests
[W 210723 06:34:30 health:209] Unhealthy services: [{'service': 'Docker registry', 'ok': False}]
[E 210723 06:34:30 log:140] 503 GET /health (anonymous@172.27.188.104) 840.07ms
```
It looks like every time we GET /health, it queries the registry to fetch some data, and we're querying it so much that dockerhub is deciding to ratelimit us. I have a Discord bot (tablesetter) that does health checks every 30s, which is very aggressive and triggered the ratelimiting. I've toned it down to once every 5 mins (10x slowdown) so hopefully this issue goes away. Interestingly enough we've been doing this for a very long time and only recently did it start becoming an issue. This is also another big reason to #213 as dockerhub is not the nicest registry and has very stringent ratelimiting (e.g. you can only pull 100 images per 6 hours based on IP), and in the case we're ratelimited and pods need to pull an image, we're at risk of the pod getting stuck in `ImagePullBackoff` as it can't grab its image.

**Comment by TimStewartJ** [comment]
Here's some relevant info on dockerhub's general rate limiting that we appear to be effected by: https://docs.docker.com/docker-hub/download-rate-limit/

![Screenshot of dockerhub rate limit](https://user-images.githubusercontent.com/37033036/126746218-1dd98f60-146d-43c5-9376-a1d2a901bc20.png)

**Comment by sandertyu** [comment]
It seems that the changes to the discord bot have allowed images to be properly accessed again. We'll let it set for a while though just to make sure that everything is okay.

**Comment by sandertyu** [comment]
This has been fixed and we've gotten no binderhub issues.
