### ISSUE TITLE
Add power outage documentation

### ISSUE THREAD

**Issue by rfeltstykket** [LibreTexts/metalc#244]
Here is the process that Tom followed when he was bringing the cluster back online:
        Restarted all of the firewalls, blackhole
        Restarted all of the nebula nodes
        Restarted all of the star nodes

**Comment by TimStewartJ** [comment]
I've started work on a power outage doc in the troubleshooting folder: https://github.com/LibreTexts/metalc/blob/update-docs/docs/Bare-Metal/troubleshooting/PowerOutage.md

I'm not sure how specific we need to be with it.

**Comment by TimStewartJ** [comment]
To be merged in #245
