### ISSUE TITLE
Add jupyterlab-git

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#247]
https://github.com/jupyterlab/jupyterlab-git

**Comment by TimStewartJ** [comment]
Added in 3.2.0: https://github.com/LibreTexts/default-env/pull/59

**Comment by TimStewartJ** [comment]
Okay, it doesn't seem to be as easy as I thought it was. Recent builds are having an issue where launch times are inconsistent and usually long. I'll try pinning more packages and see if that helps.

**Comment by moorepants** [comment]
There is some work on making pinning work better for conda. For example https://github.com/conda-incubator/conda-lock. Maybe we should look into doing this. We should be pinning with `==`, but it is hard to manage that with only the top level installs because in the past sometimes it failed to build at a later date even though it did at an earlier date. I'm not sure why that is (it shouldn't happen), but it does. Just exported an environment.yml file of the current environment has some issues too because it doesn't fully capture all needed info. Thus conda-lock, which is supposed to help solve those issues.

**Comment by TimStewartJ** [comment]
Oh okay, I'll look into that. Also I've been using `=` since that's what the conda env export uses as well. Pip seems to use `==` however.

**Comment by TimStewartJ** [comment]
Turns out the issue was likely due to the image simply not being cached on all of the nodes. This should now be the case and everything has been updated to the newest default env. Closing.
