### ISSUE TITLE
Users should be able to add custom (docker) environments to the server spawner page

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#25]
We'd like for instructors to be able to create environments based on these supported methods: https://repo2docker.readthedocs.io/en/latest/config_files.html#config-files

For now, we should add instructions to the spawner page that direct users to email us these files (or locations of the file, i.e. dockerhub) and we can manually add them. We will need to curate these and organize them on the spawner page as they grow, but should be selective about what we put up. Maybe there is a method for allowing users to use their custom files without over populating the spawner page with tons of environments. 

I'm imaging that we would see the default environment and environments for specific classes or textbooks.

**Comment by moorepants** [comment]
We can likely support this set of environments pretty easily since it is maintained by Jupyter: https://github.com/jupyter/docker-stacks/

**Comment by celine168** [comment]
There are also several repositories where you can use repo2docker to create Docker images: https://github.com/binder-examples

**Comment by moorepants** [comment]
Nice. We'll need to make some kind of list of the ones we want to support I suppose. I can help look through them.

**Comment by moorepants** [comment]
We have a solution for this and instructions are now available to users.
