### ISSUE TITLE
Move Kubernetes network to the smart switch

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#26]
At the moment, the Kubernetes network is plugged into the dumb switch because netboot wouldn't work with the network plugged into the smart switch. Richard said we can have the management and Kubernetes networks plugged into dumb switches for now, but we should probably fix this for the production server.

**Comment by lux12337** [comment]
The Kubernetes network has been moved to the smart switch, it was necessary in order for the ZFS to work with the 10Gb/s connection.

**Comment by moorepants** [comment]
Great! Closing this then.
