### ISSUE TITLE
Hub tab disappears when custom Docker environment used

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#27]
I included the package, nb_conda_kernels, while using repo2docker and added the environment to the list of environments.
When doing this, the `Hub` tab in JupyterLab disappears.
Adding this as an issue for documentation.

**Comment by moorepants** [comment]
I would open an issue on the nb_conda_kernels repository about the hub tab disappearing.

Also, are you sure you are installing nb_conda_kernels in the root/base conda environment?

**Comment by celine168** [comment]
Added issue here: https://github.com/jupyterlab/jupyterlab/issues/7011

**Comment by moorepants** [comment]
Excellent issue posted there! Super thorough!

**Comment by celine168** [comment]
Thank you! 
Turns out the Control Panel/Log Out buttons were moved to the File menu when based off the minimal notebook. I can't believe I didn't notice before 😮
