### ISSUE TITLE
Useful articles

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#29]
* [One year using Kubernetes in production: Lessons learned](https://techbeacon.com/devops/one-year-using-kubernetes-production-lessons-learned) 
* [Removing worker nodes to update them](https://cloud.ibm.com/docs/containers?topic=containers-update)
* [Understanding kubernetes networking: ingress](https://medium.com/google-cloud/understanding-kubernetes-networking-ingress-1bc341c84078)
* [Keep your Kubernetes cluster balanced: the secret to High Availability](https://itnext.io/keep-you-kubernetes-cluster-balanced-the-secret-to-high-availability-17edf60d9cb7)
* [ETCD Cluster](https://medium.com/@uzzal2k5/etcd-etcd-cluster-configuration-for-kubernetes-779455337db6)

**Comment by celine168** [comment]
* [High Availability Clusters Using Kubeadm](https://medium.com/velotio-perspectives/demystifying-high-availability-in-kubernetes-using-kubeadm-3d83ed8c458b)

**Comment by moorepants** [comment]
Should this be moved into the documentation and this issue closed?

**Comment by moorepants** [comment]
Please incorporate this in to the documentation and then close this issue.

**Comment by celine168** [comment]
Moved links in this https://github.com/LibreTexts/metalc/commit/dade8ef6531b26abc690a4e0d7d6c30d42da0de4
