### ISSUE TITLE
Setup binder on the cluster

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#3]
- [x] Figure out if binder is installed, can users still log in to jupyterhub for persistent storage.
- [x] Determine if you can point a single IP to each of the two services (jupyterhub and binder).
- [x] Decide on a domain name (we can start with jupyter.libretexts.org and binder.libretexts.org, for example).
- [x] Double check we can use the jupyter and binder names under their trademark rules, see #8 
- [x] At a minimum only allow some specific users to log in (us) or get the google authentication working. We need it secure before makign public.

**Comment by moorepants** [comment]
@celine168 @zxcGrace I've added some todo items here, please add/edit based on our meeting.

**Comment by celine168** [comment]
BinderHub should now be accessible in http://10.0.1.56/ if you log into rooster.
JupyterHub should still be accessible, just on a different IP on the cluster network (http://10.0.1.54/).

**Comment by celine168** [comment]
> Figure out if binder is installed, can users still log in to jupyterhub for persistent storage.
I'm going with yes, because I can create a notebook while running binder at the same time.

**Comment by celine168** [comment]
@Miniland1333, could we please set up a domain name for jupyter.libretexts.org?

**Comment by Miniland1333** [comment]
Sure! Where do you want the DNS record to point?

**Comment by celine168** [comment]
Would it be possible to point both jupyter.libretexts.org and binder.libretexts.org to http://128.120.136.26/?
Thank you!

**Comment by Miniland1333** [comment]
They should now both be active! I would recommend setting up LetsEncrypt on those whenever you have time.

**Comment by celine168** [comment]
Thank you!

As of now, JupyterHub and BinderHub are accessible via two different public IP addresses (assigned by the load balancer). I realized that technically we could have the two domain names pointed at each of them. However, it might be possible to have a single IP address for the two different domains, I'm not sure if one is better practice than the other though.

**Comment by celine168** [comment]
@Miniland1333 Could you please point jupyter.libretexts.org to 128.120.136.54 and binder.libretexts.org to 128.120.136.56 instead? Thank you!

**Comment by Miniland1333** [comment]
They should be updated by now!

**Comment by celine168** [comment]
> Determine if you can point a single IP to each of the two services (jupyterhub and binder).

I'll write what I found last week here. I would say no, I couldn't find a way to do this. I don't think this would be a good idea either because Binder would rely on JupyterHub running on a node, and if JupyterHub goes down, so will Binder (at least I believe so).

**Comment by Miniland1333** [comment]
In the past I've used a [NGINX reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to have a server manage multiple subdomains from a single IP address. I currently can't think of a situation where having both services on the same IP would be beneficial, but this option is available to you if you ever need it.

**Comment by lux12337** [comment]
Hi @Miniland1333, could I get the domain name binderhub.libretexts.org for http://128.120.136.55 ?

**Comment by moorepants** [comment]
If we did jupyter.libretexts.org instead of jupyterhub.libretexts.org, shouldn't we do binder.libretexts.org?

**Comment by lux12337** [comment]
@moorepants  http://128.120.136.55 is actually the jupyterhub used to run binder, so it currently doesn't have a domain name and when a user loads a repo in binder they get redirected to the ip address. Would you suggest using another name instead of binderhub.libretexts.org?

**Comment by moorepants** [comment]
Do we need more that two domain names? All that should be exposed to users is a Jupyterhub login and a binder default page, right? I prefer the shorter urls if that is all we need: jupyter. vs jupyterhb.

**Comment by Miniland1333** [comment]
![image](https://user-images.githubusercontent.com/12994749/61492295-e4631300-a965-11e9-99a0-43ed43832a43.png)
These are now all of the active subdomains for your team. Let me know if these ever need changing or if you are no longer any of these.

**Comment by lux12337** [comment]
@moorepants I think we do need to have another domain name specifically for the jupyerhub under binder as it is a separate service that runs on the cluster, and it has to be accessible by users outside of the cluster. The jupyterhub under binder is setup in such a way that is it not accessible directly without going through binder first. I looked at other binder deployments from other organizations and have found a similar setup:
  - Pangeo:
    - Binder: https://binder.pangeo.io/
    - JupyterHub under binder:  https://hub.binder.pangeo.io
  - OVH:
    - Binder: https://binder.mybinder.ovh/
    - JupyterHub under binder: https://hub-binder.mybinder.ovh
 
Ideally they would both be under the same domain for binder but from what we've seen so far, we're not sure if it's possible.

**Comment by moorepants** [comment]
Ok, I think I understand now. Will this work?:

- jupyter.libretexts.org : url libretexts and ucd users go to to have a persistant jupyterhub session
- binder.libretexts.org : url that libretexts pages can access for using binder to power the jupyter enabled pages (will likely not have public access -- public usrs should be directed to berkeley's binderhub)
- binderhub.libretexts.org : the jupyterhub that binder.libretexts.org uses (no public access)

**Comment by lux12337** [comment]
@moorepants That would work yes, currently the domain for the jupyterhub that binder uses is https://jupyterhub.libretexts.org, @Miniland1333 could you change the domain for jupyterhub.libretexts.org to binderhub.libretexts.org? Thank you!

**Comment by moorepants** [comment]
Is there such a thing as "binderhub"?

**Comment by moorepants** [comment]
I see the pangeo and mybinder call them "hub binder". Maybe copy that. This means the "jupyter hub that binder uses".

**Comment by lux12337** [comment]
@moorepants is hub.binder.libretexts.org ok then?

**Comment by moorepants** [comment]
sorry to be back and forth, i think just stick with binderhub.libretexts.org (that is the jupyterhub for binder). looks better

**Comment by lux12337** [comment]
@Miniland1333 just to confirm, the final decision for ip http://128.120.136.55 will be the domain name binderhub.libretexts.org thank you!

**Comment by Miniland1333** [comment]
128.120.136.55 now is related to binderhub.libretexts.org instead of jupyterhub.libretexts.org.

Are any of you still using jupyterteam.libretexts.org related to 35.188.48.29?

**Comment by lux12337** [comment]
@Miniland1333 thank you! I'm not sure about jupyterteam.libretexts.org is being used for as that ip doesn't look familiar to me at all. @celine168 do you have an idea?

**Comment by celine168** [comment]
I assumed jupyterteam.libretexts.org is the mailing list for jupyterteam.

**Comment by Miniland1333** [comment]
Ah, in my email Xiaochen had a "jupyterhub IP address 35.188.48.29" and wanted a subdomain for it. I temporarily assigned her jupyterteam.libretexts.org, but since it doesn't look like it is it being used anymore I will remove the DNS record. The mailing list address different and is on the ucdavis domain.
