### ISSUE TITLE
Nginx failed to restart after unattended-upgrades

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#30]
After unattended-upgrades ran this morning at 7am, nginx failed to start and we had to restart it manually. We were thinking that in production we wouldn't want to have the upgrades break something bringing our services down, so maybe we should manually run upgrades periodically so that we can fix anything that goes wrong on the spot?

Nginx logs:
```
â nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-07-31 06:54:51 PDT; 2h 54min ago
     Docs: man:nginx(8)
  Process: 1300 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jul 31 06:54:50 rooster systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 31 06:54:51 rooster nginx[1300]: nginx: [emerg] bind() to 128.120.136.54:80 failed (99: Cannot assign requested
Jul 31 06:54:51 rooster nginx[1300]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 31 06:54:51 rooster systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 31 06:54:51 rooster systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 31 06:54:51 rooster systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

`tail /var/log/apt/history.log` lists `Start-Date: 2019-07-31  06:51:44` for an unattended upgrade.

**Comment by moorepants** [comment]
If you have a staging cluster, then you can run upgrades there first. If they work, then apply to production. That's fine, but we need to have an ongoing task that someone has to attend to. If we only apply upgrades from ubuntu-security, those typically don't break anything. It worries me now that everytime I ssh into rooster that the first thing I'm greeted with is "packages need updating, x number of security". Did your unattended upgrades only install security updates or did it try to upgrade everything?

**Comment by moorepants** [comment]
Closing in favor of keeping this conversation in #4.
