### ISSUE TITLE
Unable to access account after taking down a node

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#35]
We took down chick9.
Chick9 was running the `proxy-xxx` pod and a pod for one of my JupyterHub accounts.
Good news: JupyterHub is still alive and running. The `proxy-xxx` pod got reassigned to another chick.

Bad news: I can't access my JupyterHub account anymore.
More details: 
1. My pod ended up getting stuck on a `Terminating` state on chick9, but the cluster couldn't terminate it since chick9 was down. 
1. When chick9 was plugged back in, it finished terminating the pod since it did not appear in the pod list anymore. chick10 went down (we have no idea why), so we had to get chick10 back up. 
1. I tried accessing JupyterHub, but it automatically redirected to my account, which the cluster didn't make a pod for. So the only way I could access JupyterHub was by going in a private window or clearing my cookies.
1. If I try to log into my account, it gets stuck after logging in and gives me this error:
![accterror](https://user-images.githubusercontent.com/22624020/63406399-a01cc580-c39e-11e9-98b4-33214252acae.PNG)

Had a busy afternoon so I will be looking into the logs more.

**Comment by celine168** [comment]
So I upgraded JupyterHub and deleted the `hub-xxx` pod a few times and I can log back into my account. Pretty sure one of the actions let me log back in.

**Comment by celine168** [comment]
Referenced here: https://discourse.jupyter.org/t/user-pod-stuck-in-terminating-status-when-a-node-goes-down/1958

I thought about it some more and the problem is that:
* a user pod needs to be able to be culled (deleted) automatically when they're inactive
* a user pod should be able to restart automatically if a node goes down.
Not sure if the two can coexist, hopefully someone can reply on Discourse.

**Comment by celine168** [comment]
Issue with a possible reference here: https://github.com/jupyterhub/kubespawner/issues/223
Some thought process on this issue here: https://github.com/jupyterhub/kubespawner/issues/233

**Comment by moorepants** [comment]
@celine168 Is this something we need to address? Or do we know how to solve it?

**Comment by celine168** [comment]
I'm not sure how to solve it; I suspect the problem is how kubespawner works. As stated in a kubespawner issue:
> We have an issue when pods are removed unexpectedly that seems to require a hub restart. This could happen if a node fails, is preempted, or an admin deletes a user pod I think. This is really bad I'd say as it requires the specific user that has this problem to contact and administrator and then the administrator has to restart the hub to solve it.

Ideally, if a node fails, a user pod should NOT be affected. We could dig into some Python and contribute to Kubespawner (in fact, I probably would if I had more time right now).

**Comment by moorepants** [comment]
We haven't had to deal with this issue in some time (besides manually killing a pod occasionally), so closing for now.
