### ISSUE TITLE
Allow any UCD email address to log into the Hub

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#39]
It would be preferable if we did not have to approve and whitelist new UCD accounts. But we need to leave the LibreTexts manual whitelisting in place (at least until we get a better solution).

**Comment by celine168** [comment]
One way I mentioned before is to have two different JupyterHubs; one for whitelisting specific users and the other for all UC Davis accounts.

**Comment by moorepants** [comment]
Are there any downsides to operating two hubs?

**Comment by moorepants** [comment]
Let's spin up a second jupyterhub at jupyter.ucdavis.edu and have it configuration for allow only ucdavis domains.

**Comment by sandertyu** [comment]
This is now default behavior on jupyter.libretexts.org. We might move this behavior to a hub at a new domain, but I figure we can open a new more specific issue for that when we get there.
