### ISSUE TITLE
Keeping ubuntu up-to-date (security)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#4]
On my first login to rooster I saw that there were 187 possible updates with like 90+ of them being security updates. We need a best practice to keep these up-to-date especially wrt to the security issues.

- Focus on automated security updates

**Comment by celine168** [comment]
I'm reluctant to restart rooster right now as I'm afraid it might break something.

**Comment by moorepants** [comment]
We discussed automating the security updates with a cron job for this item. Would be worth asking Richard how he handles OS updates.

**Comment by moorepants** [comment]
This might work for this: https://phoenixnap.com/kb/automatic-security-updates-ubuntu

**Comment by moorepants** [comment]
From @lux12337 

After unattended-upgrades ran this morning at 7am, nginx failed to start and we had to restart it manually. We were thinking that in production we wouldn't want to have the upgrades break something bringing our services down, so maybe we should manually run upgrades periodically so that we can fix anything that goes wrong on the spot?

Nginx logs:
```
â nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-07-31 06:54:51 PDT; 2h 54min ago
     Docs: man:nginx(8)
  Process: 1300 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jul 31 06:54:50 rooster systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 31 06:54:51 rooster nginx[1300]: nginx: [emerg] bind() to 128.120.136.54:80 failed (99: Cannot assign requested
Jul 31 06:54:51 rooster nginx[1300]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 31 06:54:51 rooster systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 31 06:54:51 rooster systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 31 06:54:51 rooster systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

`tail /var/log/apt/history.log` lists `Start-Date: 2019-07-31  06:51:44` for an unattended upgrade.

**Comment by moorepants** [comment]
If you have a staging cluster, then you can run upgrades there first. If they work, then apply to production. That's fine, but we need to have an ongoing task that someone has to attend to. If we only apply upgrades from ubuntu-security, those typically don't break anything. It worries me now that everytime I ssh into rooster that the first thing I'm greeted with is "packages need updating, x number of security". Did your unattended upgrades only install security updates or did it try to upgrade everything?

**Comment by moorepants** [comment]
@lux12337 Also, ask Richard how he handles this for his clusters.

**Comment by moorepants** [comment]
You can do some research on this too. For example this looks useful: https://serverfault.com/questions/104665/updating-production-ubuntu-boxes-the-dos-and-donts

**Comment by lux12337** [comment]
We have installed unattended-upgrades which checks daily for security updates. It successfully run yesterday morning and we are currently up to date for the security updates.

**Comment by moorepants** [comment]
After reading that link I sent and getting advice from Richard, do you think automating this is a good idea? I've always done it manually in the past for my personal servers, for example, but it would be nice to not have to worry about it.

**Comment by lux12337** [comment]
I think doing manual upgrades would be a better choice so we can be ready if anything goes wrong. Should i turn off the automatic upgrades then?

**Comment by moorepants** [comment]
Yes, if you think that is the safe thing to do, let's turn off the manual updates and then add to the documentation the steps one needs to take to do security updates safely. We can then make that a ongoing tasks for one of you all.

**Comment by lux12337** [comment]
Unattended upgrades have been turned off.

**Comment by lux12337** [comment]
Closing because we are going to setup manual updates.

**Comment by moorepants** [comment]
Have you added the instructions for manually updating to the documentation? If not lets keep this open until the process is defined, documented, and implemented.

**Comment by lux12337** [comment]
Reopening because the process hasn't been defined yet.
