### ISSUE TITLE
Create a JupyterLab help menu item to contain documentation specific to our JupyterHub

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#41]
Once a user is logged in and sees JupyterLab, it would be nice to have a menu item under "help" that houses our custom help documentation for our users and specific hub installation. This could be a FAQ and items on our front page can be moved there.

**Comment by sandertyu** [comment]
I think this has been accomplished by our current FAQ? Or are we planning on adding more technical things about the cluster setup?

**Comment by moorepants** [comment]
Yes, this is solved. Closing.
