### ISSUE TITLE
Setup appropriate and reasonable grafana alerts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#43]
We had the alerts running but it was sending out too many false positives. These need to be tuned and turned back on so we can make use of them.

**Comment by celine168** [comment]
I think Grafana alerts are more accurate now since Luigi raised the thresholds. I don't remember getting a false positive in the last week or so.

**Comment by lux12337** [comment]
Email alerts have been turned on for when:
 - A node uses more than 90% of their CPU/RAM.
 - The cluster as a whole uses more than 90% of CPU/RAM.

**Comment by moorepants** [comment]
@lux12337 Once you get the alerts back up please close this issue.

**Comment by moorepants** [comment]
@lux12337 I've moved this to high priority.

**Comment by moorepants** [comment]
@lux12337 Have you setup appropriate alerts? If so, please close.

**Comment by lux12337** [comment]
The alerts should be good for now, closing.
