### ISSUE TITLE
Install packages for Lindsay Poirier's course

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#45]
See the install.R file here: https://github.com/lindsaypoirier/STS-101

If we can add her packages to the default environment, do that, else create a custom spawner for her course.

**Comment by moorepants** [comment]
All of the requested packages are available on conda forge:

- https://anaconda.org/conda-forge/r-leaflet
- https://anaconda.org/conda-forge/r-shinydashboard
- https://anaconda.org/conda-forge/r-httr
- https://anaconda.org/conda-forge/r-rmarkdown
- https://anaconda.org/conda-forge/r-tidyverse

**Comment by moorepants** [comment]
PR here: https://github.com/LibreTexts/default-env/pull/13

**Comment by celine168** [comment]
I was about to add them; I'm assuming to ignore the other folders in her repository.

**Comment by moorepants** [comment]
I don't know, you can ask her. @lindsaypoirier, do we need to install packages from all folders?

**Comment by moorepants** [comment]
I don't see any other install.R files except the top level one.

**Comment by lindsaypoirier** [comment]
The other folders are just storing datasets. Just the top level install is fine.

**Comment by celine168** [comment]
@lindsaypoirier The packages have been added to the Default Environment, let us know if there are any issues!

**Comment by moorepants** [comment]
I'm not able to load shinydashboard or leaflet:
![2019-08-30_14-53](https://user-images.githubusercontent.com/276007/64053145-0390bb00-cb36-11e9-8e14-18fef56d7b09.png)

**Comment by celine168** [comment]
That's strange how they didn't install. I removed `r-essentials` and the requested packages seem to work now.
You can use the packages but there's some visual glitching in JupyterLab, most likely due to this: https://github.com/jupyterlab/jupyterlab/issues/7122 Will update JupyterLab.

**Comment by celine168** [comment]
All of the packages are added (and no more glitching)!
You can also access RStudio through our JupyterHub now, if you change the `/lab` to `/rstudio` in the URL after signing in.

The packages that fire up a webserver, `shiny` and `shinydashboard`, don't seem to work well in Jupyter notebooks, but they work completely fine in the RStudio attached to our JupyterHub.

**Comment by moorepants** [comment]
@lindsaypoirier Celine enable rstudio on the hub. If you change the last part of the url from `lab?` to 'rstudio` you can try it out. Can you see if all your materials works as intended? The shiny dashboard may work with rstudio.

**Comment by moorepants** [comment]
@lindsaypoirier Can you confirm that these packages are working for you as desired? The shiny based ones should work from the Rstudio interface.

**Comment by lindsaypoirier** [comment]
@moorepants This works out well. Thank you!
