### ISSUE TITLE
We need a recommended method for distributing files to students' jupyterhub account

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#46]
Instructors need to populate student directories with up-to-date files that they need for their assignments but we do not give insturctors adminstrator access, so we need a recommend (simplest) method for them to do this. +1 if it works intuitively with files hosted on LIbreTexts pages.

**Comment by moorepants** [comment]
Note this open issue: https://github.com/jupyterhub/jupyterhub/issues/394

**Comment by celine168** [comment]
At Berkeley, they use nbgitpuller for distributing assignments and okpy for grading. Refer to: https://github.com/jupyterhub/helm-chart/issues/47 

I have not tested nbgitpuller yet as my personal JupyterHub is down and we may need another IP to get another JupyterHub going on our cluster.

That issue contains other links to issues related to grading, which I will discuss in our grading issue.

**Comment by celine168** [comment]
I suggest using nbgitpuller, we can add them to custom environments for classes and they will pull up-to-date repos. I will add this to the front page.

**Comment by moorepants** [comment]
The nbgitpuller sounds like a good way to have something in place for this.

**Comment by moorepants** [comment]
So this is solved for now with: https://github.com/LibreTexts/jupyterhub-templates/pull/2
