### ISSUE TITLE
Scale Production Cluster for Fall Quarter

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#48]
After meeting with Richard, he suggested we scale up our current cluster to meet the demand for Fall quarter. We will scale up in two ways:
 - [x] Add more worker nodes
   - [x] Rack 9 additional worker nodes
   - [x] Add worker nodes to the Kubernetes cluster
 - [ ] Upgrade the RAM of the old worker nodes from 16GBs to 64GBs
   - [ ] Chick0
   - [ ] Chick1
   - [x] Chick2
   - [x] Chick3
   - [ ] Chick4
   - [ ] Chick5
   - [ ] Chick6
   - [x] Chick7
   - [x] Chick8
   - [x] Chick9
   - [x] Chick10

**Comment by moorepants** [comment]
Nice!

**Comment by lux12337** [comment]
I'm going to hold off from upgrading the RAM on some of the chicks that are running critical pods such as the hub itself and the autohttps pod. Shutting down those nodes will disrupt the service, and adding more nodes for increased demand is easier/safer. 

Also as i mentioned in our last meeting, netboot on the smart switch is unreliable as sometimes a new node won't be able to acquire an ip address from the DHCP. We are speculating that a reason could be how the smart switch is configured, but didn't want to mess it with since we are in production. Our workaround has been to setup another rooster under our current rooster and have it run a DHCP server on a dumb switch with an ip range of 20.0.0.X. In this way, we can setup new nodes with netboot on the dumb switch first and then transfer them over to the smart switch and add them to the Kubernetes cluster. 

With this setup, we could potentially build a staging cluster using the rooster under our current rooster. Also, we have run into a lot of problems with hard drives and haven't been able to add new nodes yet.

**Comment by lux12337** [comment]
8 more nodes have been added to the cluster, chick12-chick18, there are still 4 spots left on the switch, we might just fill up the entire switch.

**Comment by moorepants** [comment]
@lux12337 Would you say this is done? If so, we can close the issue. If you want to upgrade ram on all nodes we should do it over winter break.

**Comment by lux12337** [comment]
I think we have enough resources for this quarter, and should now focus on v2. I will go ahead and close this.
