### ISSUE TITLE
Chick10 keeps going down

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#49]
Chick10 has a history of going down when another node goes down. This happened twice in the past.

**Comment by moorepants** [comment]
I recommend asking Richard for advice. Is the hardware just bad?

**Comment by moorepants** [comment]
Does this affect users that have pods on chick10 and an adverse way?

**Comment by moorepants** [comment]
Is this still the case?

**Comment by lux12337** [comment]
chick10 hasn't gone down again after the first time. I will check the plug is seated correctly as suggested.

**Comment by moorepants** [comment]
Hasn't happened in a while.
