### ISSUE TITLE
Doing a fork bomb prevents other users' servers to spawn

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#50]
### Problem
Per suggestions from the meeting, we did a fork bomb last night on Luigi's account. Luigi's user pod froze and my accounts (which were also running on JupyterHub) also froze. New servers and our servers could not spawn afterwards; you would either get 504 Gateway errors or 'unable to connect to server errors'. 

Luigi's pod was on chick7. Trying to create a server on chick7 would lead to an error in the progress bar saying `Unable to mount volumes for pod <pod-name>: timeout expired waiting for volumes to attach or mount for pod <pod-name>...`

### The Immediate Fix (rather technical)
We tried a couple of methods including,
* upgrading JupyterHub
* deleting pods with `--grace-period=0` and `--force` (which deletes them from the API but doesn't actually delete the containers running in the pod)

After this we found that pods could spawn as long as they did not choose to spawn on chick7.

We also saw that the Docker containers for our accounts were still running by running `sudo docker container ls`. We could not delete the containers through commands like `sudo docker rm <container>` as they would stall.

In the end, we restarted chick7 and those Docker containers disappeared.

### Preventing This From Happening Again
We do already have CPU and memory limits for user pods, so I'm surprised of how much the fork bomb affected. 

#### Some questions to consider:
* Is this an issue with Docker containers?
   I looked into [Kubespawner](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html) but they don't seem to have any options for setting more limits apart from memory or CPU. Perhaps the Docker container ran out of RAM and stalled as a result? 
* or is this an issue with the node itself?
   Eventually, any server that tried to spawn on chick7 would give an error, but spawning on other chicks would be successful.

**Comment by moorepants** [comment]
Conclusion at meeting was to ask on appropriate mailing lists how others handle this issue.

**Comment by celine168** [comment]
Posted in the [Docker forums](https://forums.docker.com/t/fork-bomb-stalls-other-docker-containers/81903)

**Comment by celine168** [comment]
Some thoughts on PID limits here: https://github.com/jupyterhub/kubespawner/issues/303

**Comment by moorepants** [comment]
Was this on chick5 that had the bad disk?

**Comment by moorepants** [comment]
We have to wait till having version 2 cluster to do this, right? Or is it safe to fork bomb a pod on production?

**Comment by celine168** [comment]
If we do test the fork bomb on the main cluster, it would be best if:
* the pods on the node affected aren't as important
* we do it when there are little to none users on JupyterHub

There's a possibility that new user pods would get scheduled on that chick so that chick would need to get unscheduled.

**Comment by moorepants** [comment]
We can move to version 2 cluster then or wait till winter break.

**Comment by moorepants** [comment]
This is old and we can address in #16.
