### ISSUE TITLE
Grafana data is lost after a pod restart/crash

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#51]
This is a known problem with not a clear solution. Some options are discussed [here](https://github.com/coreos/prometheus-operator/issues/1637).

**Comment by moorepants** [comment]
We agreed that a snapshot of the json config file should be created and we manually recreate the alerts if this ever goes down (for now). You can monitor the proper solutions as time passes.

**Comment by moorepants** [comment]
json file is stored in metalc-configurations
