### ISSUE TITLE
Contain PSAD

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#56]
PSAD sends alerts based on suspicious activity in IP tables. These suspicious IP addresses should:
* be confirmed whether they are safe
* and take appropriate action if they are unknown.

Issue extended from Cluster/Server Hardening: https://github.com/LibreTexts/metalc/issues/12

**Comment by moorepants** [comment]
@celine168 What priority should this issue be?

**Comment by celine168** [comment]
Low to medium.

**Comment by rkevin-arch** [comment]
Not sure what "contain" PSAD means. Pretty sure we have that deployed and it's occasionally adding iptables rules to ban IP addresses, then removing them after a while. I'm going to close this issue in a day or so if no one responds.

**Comment by moorepants** [comment]
We had an issue of PSAD logging very large files and filling up disk space on ?rooster? I believe. Contain means to set the logging so it discards old logs. I think.

**Comment by rkevin-arch** [comment]
Rooster seems to have plenty of disk space left (using 80G/1.7T) so I'm not sure if this is an issue.

**Comment by moorepants** [comment]
In general, we should ensure that all logs in /var/log on any node actually delete old logs. It may not be an issue anymore, as the logging have have been fixed.

**Comment by rkevin-arch** [comment]
I'm not sure how the log files overflowed, since logrotate would already guarantee old logs are deleted. I'm gonna tentatively close this issue since it shouldn't be a problem to begin with.

**Comment by moorepants** [comment]
I don't think logrotate was enabled or working for PSAD. Hopefully it is now.
