### ISSUE TITLE
How can we add users directly to the config file without running upgrade script?

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#57]
When we run upgrade the service is down temporarily. It isn't clear what this does to logged in and working users. Ideally, we shouldn't have to do this. We can add users via the admin panel without restarting the service, so there must be a way to do so from the command line, no?

**Comment by celine168** [comment]
When we upgrade the service and nothing goes offline after the temporary
downtime, it should not affect working users. The user pods remain online
and should not go down.

However, if we're messing with something like nginx and traffic isn't being
directed to JupyterHub for whatever reason, then logged in users will
experience downtime as well.

**Comment by moorepants** [comment]
I just added users for my class this morning and when I ran upgrade.sh it takes 20 seconds or something. If I try to access jupyter.libretexts.org it says "temporarily unavailable". So it seems to shut down access during the upgrade.

**Comment by lux12337** [comment]
When adding users to the hub, it is enough to just add the users through the admin page and add them to the config file without upgrading. Users should be able to access their hubs as soon as they are added to through the admin page. The reason we add them to config file too is that in the case we change the configurations in the future, an upgrade would create the user lists with the users defined in the config file.

**Comment by celine168** [comment]
`upgrade.sh` takes some time to run but the actual downtime of the login page is shorter. 

I did some testing and upgrading JupyterHub does interrupt the kernels of logged in users for about 5-10 seconds but works fine afterwards. If you happen to run something during an upgrade, you might have to reselect your kernel.

**Comment by celine168** [comment]
Javascript file for where users are added from the admin panel: https://github.com/jupyterhub/jupyterhub/blob/c8c39aa40d6b63083e2fe7a719b1712f36a50a61/share/jupyterhub/static/js/admin.js#L220-L246

I want to say that it uses the [JupyterHub Rest API](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html) but I'm not sure.

**Comment by moorepants** [comment]
> When adding users to the hub, it is enough to just add the users through the admin page and add them to the config file without upgrading.

This seems fine. I can do that from now own. Paste the list in the admin page (as long as I can add them in batch fashion). Then paste into the config file but don't upgrade

It think it would be worthy asking on the jupyter communication channels how you are supposed to programmatically add users without upgrading the hub.

**Comment by moorepants** [comment]
Someone needs to investigate why you can add users via the jupyter admin panel and the config file and what the differences are. These ideally should be in sync. If we can delete the users from the config file that would be ideal. See issue #53 also, as it is related. We need a way to track the type of user until we have better user authentication and the jupyter config file is not amenable to adding the tracking info we want.

**Comment by moorepants** [comment]
Closing this. We've just been using the Jupyter admin panel and haven't kept the user list up-to-date as it is too much work.
