### ISSUE TITLE
"Export Notebook As..." pdf returns a 500 error

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#60]
Had a Python 3 notebook open and tried to convert to PDF and got this:

![Selection_582](https://user-images.githubusercontent.com/276007/65719012-ae26cb80-e059-11e9-870f-1f2940508aaa.png)

It could be that we don't have texlive installed via apt. We need to install `texlive-full` in the dockerfile if it isn't.

**Comment by celine168** [comment]
Are you talking about `File | Print | Print to PDF`? That function seems to work for me.

**Comment by moorepants** [comment]
It is "Export Notebok As." -> "PDF"

I am pretty sure we just need to have `texlive-full` installed in the default docker container.

**Comment by moorepants** [comment]
I am still getting this error. If texlive is installed, then more investigation is needed to figure out how to download a notebook as a pdf.

**Comment by moorepants** [comment]
Maybe a related issue: https://github.com/jupyter/notebook/issues/4311

**Comment by moorepants** [comment]
Also potentially relevant: https://stackoverflow.com/questions/55013206/how-can-i-fix-500-internal-server-error-on-jupyter-notebook-due-to-tornado

**Comment by tkumar98** [comment]
updated NBConvertor, did not use texlive-full. exporting as pdf works nows
