### ISSUE TITLE
Setting up node problem detector and draino

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#62]
User pods running on chcik5 get stuck after Kubernetes tries to terminate them. This has previously happened in the past when testing fork bombs on chick5. Richard told us that he checked chick5 and there is a bad drive on it, that is probably the cause of the malfunction.

**Comment by moorepants** [comment]
We also need an alert for this. Can you make it a priority to get the grafana alerts back up and ensure that we'd get an alert about this?

**Comment by moorepants** [comment]
I think I'd call this high priority, because if not attended to users are stuck and can't log in.

**Comment by lux12337** [comment]
Just noticed that one of the user pods on chick4 is not terminating. I checked the drives on chick4 and it seems like one of the drives on chick4 failed too. I'm afraid that since all the drives that we have on our older nodes have similar lifetimes, they might start failing too. This is something we can discuss with Ricahrd to see if he has any suggestions.

**Comment by lux12337** [comment]
chick4 has been drained, no pods can be scheduled on there anymore.

**Comment by moorepants** [comment]
I can buy new drives if that is what we need.

**Comment by moorepants** [comment]
Another that that needs to be looked into here is how to terminate users if this happens. We should be able to detect if a node is having issues and safely move logged in users to a good node.

**Comment by lux12337** [comment]
[node-problem-detector](https://github.com/kubernetes/node-problem-detector) looks promising, it detects various kinds of problems on a node and reports them to Kubernetes apiserver.

**Comment by moorepants** [comment]
@lux12337 Do we want to setup this node-problem-detector? If you think it is a good idea, we can have someone do that.

**Comment by lux12337** [comment]
i'll work on it

**Comment by lux12337** [comment]
The node problem detector can be used in conjunction with [draino](https://github.com/negz/draino). Draino will drain nodes that are marked problematic by node-problem-detector.

**Comment by rkevin-arch** [comment]
node-problem-detector has already been deployed a long time ago. If you want, we can also set up draino. Let us know if that's the case.

**Comment by moorepants** [comment]
Once we get more users I'm guessing we will start to see these issues again. We would have user pods stop functioning from time to time. So we may need these services.

What is node-problem-detector doing? Does it sends us alerts?

**Comment by rkevin-arch** [comment]
It doesn't send alerts, but it sets node conditions that can be queried from kubectl. It should also be exposed in prometheus, so we might be able to hook a Grafana alert up to it. Adding to the TODO list.

**Comment by moorepants** [comment]
Closing this as old and we can reopen as needed.
