### ISSUE TITLE
Google is throttling our alerts (look in the sys log)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#63]
Switch to campus SMTP server

**Comment by celine168** [comment]
By this, do you mean we should switch the outgoing email to a UCD email address?

**Comment by moorepants** [comment]
Yes, you can you make use of UC Davis's mail server. smtp.ucdavis.edu

I don't think you need credentials if the request originates from the UCD network. You can put the jupyterteam@ucd email address as the sender.

**Comment by moorepants** [comment]
@lux12337 Is this fixed? I thought I heard that someone switched the email server. If so, please close.

**Comment by lux12337** [comment]
This has been fixed, i have switched over our Grafana to use the ucdavis smtp server. Closing issue.

**Comment by moorepants** [comment]
Ok, make sure this is documented.
