### ISSUE TITLE
Spec and order SSD harddrives for the chicks

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#66]
Richard said he'd get a got. @celine168 and @lux12337 can one of you be in charge of making sure this happens. Once there is a quote I can put in the order.

**Comment by celine168** [comment]
Luigi and I discussed this and noticed that since the nodes use on average ~150GB (@lux12337 please confirm). Richard recommended ordering drives with twice the amount. We think that 500 GB hard drives should be good, just to be safe (since Docker images can take up a lot of space). May be beneficial to double check with Richard to make sure it's okay.

**Comment by moorepants** [comment]
Interesting that the docker images are on the nodes. It would potentially be nice if the the docker images and caches of them lived on the NFS server (as long as the data throughput was still fast). Then we could have inexpensive smaller SSDs on the nodes. Any idea if these are options that can be configured to have it setup like that?

**Comment by moorepants** [comment]
Actually, 500 GB are pretty cheap: https://www.newegg.com/p/pl?d=500+gb+ssd

We'd need like 40 drives for the current nodes? So maybe we can get them for $2k?

**Comment by lux12337** [comment]
Yes, the nodes do use around 150GB~ so far, so 500GB should be good. I was thinking of adding 4 more nodes to fill up the smart switch we have, so that would mean 46 drives if that's possible.

**Comment by lux12337** [comment]
We might need to order more drives than that if we want to start building the v2 of the cluster soon.

**Comment by moorepants** [comment]
Notes from discussing with Richard last week:

- If we need some backup drives for the current cluster we can by two pairs to have on hand. Send Jason a link to what you want to buy if you want these.
- Let's hold off on buying all the drives. We should buy all new drives for the version 2 cluster.
- Richard recommended samsung drives from newegg. Intel as the second choice in brands.

**Comment by moorepants** [comment]
Closing this as it isn't that relevant anymore.
