### ISSUE TITLE
Create instructions for fixing users if chick goes down

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#67]
We need a clear set of instructions to get things back in order if a chick goes down. Richard suggested we have these in the alert email reporting a downed chick.

**Comment by celine168** [comment]
I started this document: https://github.com/LibreTexts/metalc/blob/master/docs/Bare-Metal/troubleshooting/GeneralTroubleshooting.md

**Comment by moorepants** [comment]
!!! "First, scream." !!! :scream:

**Comment by celine168** [comment]
I try to add some humor when I can, but please let me know when I should take it out or avoid it!
If there is something not clear in the document, please let me know about that too.

**Comment by moorepants** [comment]
Please add humor! I'm all for it :smile_cat:. It's always nice to find nuggets in your docs and code that cheer you up.

**Comment by moorepants** [comment]
Closing this, since we have a base document.
