### ISSUE TITLE
Setup nbgitpuller for Dr. Poirier

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#69]
>  I have two requests. First, can I get nbgitpuller installed on https://jupyter.libretexts.org/user/lnpoirier@ucdavis.edu/rstudio/ to pull files from https://github.com/lindsaypoirier/STS-101 for students. 

@celine168 can you set this up soon?

**Comment by celine168** [comment]
Yes I'm working on it. Eduroam is kind of getting some hiccups today.

**Comment by celine168** [comment]
Just added it. Needs an upgrade for the STS 101 environment to show up.
This link should also pull Lindsay's repo into JupyterHub once JupyterHub is upgraded:
https://jupyter.libretexts.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Flindsaypoirier%2FSTS-101&urlpath=rstudio%2F

**Comment by moorepants** [comment]
So, this will be a separate environment for her students on the spawner page? (a small addition to our default env?)

If so, next time you see the hub without any users, you can upgrade.

**Comment by celine168** [comment]
Yes, it's a separate environment. It is listed as "STS 101" on the spawner page; you can see in `config.yaml`.

It will use the same Dockerfile as the default environment but essentially `git clone`'s her repository every time a user spawns a server.

**Comment by moorepants** [comment]
Ok, sounds good. Feel free to upgrade when it looks appropriate to do so.

**Comment by celine168** [comment]
I upgraded this morning (with some difficulties, the current config.yaml doesn't reflect the current state of the hub due to a previous hub pod stalling in a Terminating state on an off chick. I deleted it from the K8s API). Lindsay's environment doesn't spawn because the nbgitpuller command doesn't seem to work. I would test it again but there are a lot of people on the hub right now so I don't want to mess with it.

**Comment by moorepants** [comment]
Can you inform her asap that even though she sees the environment, the puller isn't working yet? We don't want her to tell her class to use it if it doesn't work yet!

**Comment by moorepants** [comment]
Celine, see the emails, seems like she doesn't want it any more.

This also made me realize that setting up these docker containers for basic extensions to ours isn't as simple as I'd imagined.

**Comment by celine168** [comment]
It is fairly simple and doesn't have to do with a Docker container. It's
just adding a few lines to config.yaml. I'm very sorry for not getting it
done in time; I ran into a few errors and I forgot to try upgrading one of
these nights this week.

I think the order of which I put her class in the config.yaml might have
affected how the config file was read.

**Comment by moorepants** [comment]
@celine168 Did you inform Lindsay that the spawner doesn't work? We need to remove that spawner. I think we just got a email regarding this issue.

**Comment by moorepants** [comment]
We should remove this nbgitpuller env. But please open and issue about setting up nbgitpuller in a test environment so we can make sure we know how to do it if others want to use it.

**Comment by celine168** [comment]
Removed the STS 101 environment. Removing chick4 seemed to allow JupyterHub to upgrade.
