### ISSUE TITLE
Version control configuration scripts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#71]
We have a private repo with the configuration scripts, but we edit them manually on rooster, for example editing the JupyterHub config.yaml. A good way to manage this so that we keep things properly version controlled is to clone the private repo on the server (server user has access to the repo). This will create a directory on the server where we do the actual editing of the configuration files and can use git to track changes. The changes would be committed and push back to the private repo to keep those in sync. Then we make symlinks from the configuration locations on the server to the clone repo on the server. This means we can edit in a single place.

**Comment by celine168** [comment]
Looks like symlinks don't work. (You can see in the repo that it only stores what the symlink is in jupyterhub/jupyterhub)
Going to try mounts later.

**Comment by celine168** [comment]
Ok edit: symlinks would work if you make symlinks from the repo to the server. Feels kind of backwards but I read that that would work.
We can also do mounts on /etc/fstab now that I think about it.

**Comment by moorepants** [comment]
I do this with my servers, no problem. You git clone the repo onto the server, then you setup symlinks from the locations the config files need to be to the primary location in the clone repo. The links are all on the server. Then you only edit the files in the repo on the server and push/pull to github for keeping a remote copy. No mounts should be necessary if all config files are on rooster. If they are config files on the chicks then we need to think more about how to handle that. But as it stands, we shouldn't be manually doing anything to the chicks, right?

**Comment by moorepants** [comment]
Can you add documentation explaining the best practices with working with this, i.e. make sure the github version is always updated?

**Comment by celine168** [comment]
Added documentation here: https://github.com/moorepants/metalc-configurations/blob/master/README.md#best-practices

**Comment by celine168** [comment]
Added documentation to private repo's README.

**Comment by moorepants** [comment]
The private info is now at: https://gitlab.com/moorepants/metalc-configurations

I haven't seen any updates to this repo in months now, so it isn't clear that all these configurations are being tracked. I think it is quite important that we have good protocol with this, so that 1) anyone can access things in emergencies and 2) we can roll back configurations to prior states.

**Comment by celine168** [comment]
For future reference, I've changed the default remote repo on rooster to the GitLab one. I've also kept the GitHub repo as under the remote name `github`. 

By default on rooster, `git push` and `git pull` should automatically push and pull to the GitLab repo.
If you want to push and pull to Github, run `git push github master` or `git pull github master`.

**Comment by celine168** [comment]
I'm going to go ahead and close this since we have added documentation and the configurations repo is up to date now.
