### ISSUE TITLE
Add Tannavee to Jupyter Team on GitHub

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#73]
Could we add her to the GitHub team: https://github.com/orgs/LibreTexts/teams/jupyter-team/discussions

**Comment by moorepants** [comment]
She has yet to accept an invitation I think!

**Comment by moorepants** [comment]
I've sent two invitations, one to her ucd address and one to her github username.

**Comment by moorepants** [comment]
I've forgotten her github username. What it is it? I can send one more time.

**Comment by tkumar98** [comment]
there was an issue with my account, and I was not getting the invite notification, it's resolved and I just accepted it
