### ISSUE TITLE
Review the current blogpost

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#74]
Please review by 2019-10-25

https://github.com/mechmotum/mechmotum.github.io/pull/35

@narrator0 and @tkumar98 fyi

**Comment by narrator0** [comment]
Reviewed

**Comment by tkumar98** [comment]
Reviewed

**Comment by moorepants** [comment]
Done: https://mechmotum.github.io/blog/jupyter-summer-2019.html
