### ISSUE TITLE
SacPy Talk

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#76]
November 14, 2019
7-9 pm
Urban Hive in Sacramento

Title ideas:

- What to do when chicks go bad in your flock: JupyterHub on Bare Metal Kubernetes
- (add yours here)

Description: (help edit)

Luigi, Celine, Tannavee, Hao, and Jason will talk about setting up and running a bare metal Kubernetes based Jupyter deployment for the UC Davis population and the LibreTexts project. We will give an intro to JupyterLab, JupyterHub, and Binder then layout the nuts and bolts of what makes the system tick. We will describe the LibreTexts project and how our service will be making the open access textbooks computationally interactive. You will get to try out the services during the talk.

**Comment by celine168** [comment]
>What do to when chicks go bad in your flock

I love this

**Comment by moorepants** [comment]
Ok, I'm gonna send him what I have here.

**Comment by celine168** [comment]
Previous slides for the Jupyter Open Studio on 9/7: https://docs.google.com/presentation/d/16fGTuRP3LTM6wbnCfuhCDz25z_MKB_Dl5SsTRNmgres/edit#slide=id.p

**Comment by moorepants** [comment]
- Introduction
- What problem are we trying to solve
  - Dual education/research solution
- Goals
- What is libretexts?
- What bioinfomratic core and there needs?
  - When we need to use a cluster?
- What is Jupyter/Jupyterhub/binder?
- What is a cluster? (why bare metal)
- What is kubernetes?
- How we built the cluster?
- How we setup kubenertes?
- How we setup Jupyter/Binder?
- How is Hao?
- Problems, crazy things
 - Load balancing and netowrking
 - When chicks leave the flock?
 - https/nginx proxy
- Demo the system 
- improvements and version 2
  - redundancy haproxy
  - gpu nodes, speicalyt nodes
  - redundcay: 3 masters
  - diferent subnest for different orgs

**Comment by moorepants** [comment]
@LibreTexts/jupyter-team slides are in the drive, please help finish them up.
