### ISSUE TITLE
Setting up staging jupyterhub for testing

### ISSUE THREAD

**Issue by lux12337** [LibreTexts/metalc#78]
I have setup a staging jupyterhub on our cluster. We can use this deployment to test our configuration/environment changes before deploying to our live hub. Currently, it is reachable only by ip at http://128.120.136.61/hub/login . @Miniland1333 could we get the domain "staging.jupyter.libretexts.org"  for 128.120.136.61?

**Comment by Miniland1333** [comment]
![image](https://user-images.githubusercontent.com/12994749/68062895-5e779780-fcca-11e9-9424-aa9c9b95131e.png)

Here you go! This message got buried so I'm glad Celine brought it to my attention

**Comment by lux12337** [comment]
Thank you Henry!

**Comment by lux12337** [comment]
I have setup https and enabled OAuth. The staging JupyterHub should be good enough for configuration testing now.
