### ISSUE TITLE
Can we use the terms "jupyter", "jupyterhub", or "binder" in our domain name?

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#8]
We need to figure this out:

https://github.com/jupyter/governance/blob/master/trademarks.md#uses-that-never-require-approval

Probably just need to ask jupyter people.

**Comment by celine168** [comment]
According to the bottom of [this section](https://github.com/jupyter/governance/blob/master/trademarks.md#the-word-jupyter):

> Use of the word "Jupyter" in a domain name -- Allowed in subdomains and url-paths, such as "jupyter.example.com" and "example.com/jupyter". Not allowed in base domains, such as "jupytercloud.com" or "hostedjupyter.horse".

So I think we can use 'jupyter' as long as it's in a subdomain or url-path.

**Comment by moorepants** [comment]
Great, that's exactly what we needed! So, when we are ready with one or more IPs we can ask Henry to created them as subdomains on libretexts.org as a start.

**Comment by celine168** [comment]
I did ask someone on gitter ([link](https://gitter.im/jupyterhub/binder?at=5d1894b9ddd2c007c733a6f9)) and they thought it was ok to use binder in our domain name.

**Comment by Miniland1333** [comment]
Celine, just a quick clarification: Domain names (also known as base domains), are different than subdomains. As an example, google.com is a domain, while **maps**.google.com or **translate**.google.com are subdomains. From the link you sent above, it does look like using binder in a subdomain is ok but probably not for a domain name.

**Comment by celine168** [comment]
@Miniland1333 Oops, yes I meant subdomain. Thanks for catching that.
