### ISSUE TITLE
Improve the load time of Jupyter Enabled Libretexts pages

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#83]
In the thebelab based demo it takes some time for binder to execute and enable the page. This needs to be sped up to a tolerable speed after we get a basic implementation going.

**Comment by Miniland1333** [comment]
A related thing is whether persistent sessions such as what Juniper experimentally does is possible and usable. The downside would probably be that persistent sessions would still likely require kernel reloads which may take just as long as just using separate sessions

**Comment by tannavee** [comment]
The current load time has been significantly minimized to about 30 seconds. @celine168 should we close this?

**Comment by celine168** [comment]
I think we should wait until we switch to using our Binder first?

**Comment by moorepants** [comment]
> I think we should wait until we switch to using our Binder first?

Yes.

**Comment by moorepants** [comment]
I'd like to keep this open so we can lower it below 30 secs in the future if we can.

**Comment by moorepants** [comment]
Here is a relevant jupyter discourse post: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956

**Comment by moorepants** [comment]
@rkevin-arch @sandertyu here is an open issue on the load times.

**Comment by moorepants** [comment]
Just an update here on the current status. Kevin and Noah have converted our default docker image to one that is repo2docker compatible. This means it should now work with binder as well as our JupyterHub. Once we have that live and working on the hub (I think it is, in fact), we can test pointing the CKEditor binder plugin to our binder, so that we will more-or-less guarantee that the image is cached on all nodes and thus load times should be snappy.

**Comment by sandertyu** [comment]
Load times on LibreTexts are now under 20 seconds every single time, so I think this specific issue can be closed. They could maybe be improved further, but we can make another issue if 15-20 seconds becomes a problem.
