### ISSUE TITLE
Jupyter cells need a "i'm calculating" indicator

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#84]
When a user executes a cell it may take some time to complete or even never complete. We need a way for them to know that the calculation is occuring. And thus a "stop" button is likely needed too.

**Comment by moorepants** [comment]
sphinx-thebe implements a very clear indicator:
![image](https://user-images.githubusercontent.com/276007/96335112-4aad7880-1076-11eb-89f0-c42afb300308.png)

**Comment by moorepants** [comment]
Can we copy this indicator from sphinx-thebe (or something similar) and implement in our ckeditor plugin? That would solve this.

**Comment by sandertyu** [comment]
I think this is solved by the ckeditor binder plugin status field changes?

**Comment by moorepants** [comment]
One issue is giving more feedback on the initial connection to binder, which I think we now have. But the second issue is getting feedback when you run an individual cell. We should clarify more these two needs. I think for the second one we may need improvements to thebe.

**Comment by moorepants** [comment]
When running a cell in a Jupyterlab notebook there is this indicator:

![image](https://user-images.githubusercontent.com/276007/104005230-16dd7d00-51a5-11eb-8951-48e251d74eef.png)

That circle turns grey when the cell is calculating. There is likely a way to get thebe to tap into that signal.

**Comment by TimStewartJ** [comment]
Is this solved by https://github.com/executablebooks/thebe/pull/424? It sounds like this is what we were looking for.

**Comment by moorepants** [comment]
Yes, we just need to make a new thebe release.

**Comment by moorepants** [comment]
A spinner is now default in thebe 0.8.0. See https://github.com/executablebooks/thebe/pull/424, closing.
