### ISSUE TITLE
chick0 (master node) went down

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#87]
### Problem
chick0 went down today temporarily, due to a hardware error. 

The computer said that it corrected the hardware error itself (related to the CPU, according to the image), but we were unable to reach chick0 through SSH. It also seemed to be frozen after trying to type commands while plugged into the console. 

![image](https://user-images.githubusercontent.com/22624020/68190521-6f423a80-ff62-11e9-885b-4d0a9a6c6117.png)

### Solution
We restarted chick0. `kubectl` commands would not show the info requested (instead it showed an error), so we turned swap off by running `sudo swapoff -a`. (Side note: Many of the older nodes do not have swap turned off automatically since we didn't think of setting it off in the first place before. If you can't reach `kubectl`, turning swap off is a common fix. See [here](https://github.com/LibreTexts/metalc/blob/master/docs/Bare-Metal/troubleshooting/AddingNotReadyNode.md#solution).)

After a couple of seconds, we could use `kubectl` commands again. We then deleted a few pods that were in a bad state so they could restart themselves (namely `hub-xxx` and `user-scheduler-xxx` pods). JupyterHub seems to be in good shape now.

Saving this as an issue and to let everyone know.

**Comment by rkevin-arch** [comment]
Seems to be a stale issue, closing.
