### ISSUE TITLE
Enable C++ kernel support (like try.jupyter.org)

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#88]
We've had a request for the Jupyter notebook C++ support. Shouldn't be hard to enable that kernel in the default-env.

**Comment by celine168** [comment]
https://github.com/QuantStack/xeus-cling

We could install it in the Dockerfile via conda.

**Comment by moorepants** [comment]
We've had another request for this. It would be nice to have this working on the default-env (and then the LibreTexts pages).

**Comment by moorepants** [comment]
Let's get this done by May 1, 2020.

**Comment by celine168** [comment]
This is now live on JupyterHub, will email the professor(s) who requested this for them to perhaps add their accounts and let them test it out.

**Comment by pbmacsodak** [comment]
Just came looking for the progress. I see that kernel is running on the Hub, is there any update on the LibreText page implementation? As the semester winds down I am hoping to get working on 2 different C++ courses, one for this summer, and then the other for fall....thanks, Pat (pmcclanahan@deltacollege.edu)

**Comment by moorepants** [comment]
Hi Pat, we still have to enable for the Libretexts pages, which shouldn't be much work. See the issue here:

https://github.com/LibreTexts/metalc/issues/150

Closing this issue as complete!
