### ISSUE TITLE
Use files on LibreTexts and make them available within the Binder

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/metalc#95]
When building a repo for binderhub, LibreTexts editors would have the capability of uploading files (such as data) to the page. From there, they can modify the configuration file for the page integration such that those files are bundled into a repository for binderhub. Likely would have to include file version checking to prevent unnecessary rebuilds.

**Comment by Miniland1333** [comment]
I heard from the video presentation that this is on your todo. In order to access the files attached to a page, use this:
`let response = await LibreTexts.authenticatedFetch(undefined, `'files?dream.out.format=json')``

This API that I've created accesses information in LibreTexts/Mindtouch. The first parameter is undefined if you want to access the current page, but you can pass in either a path or a pageID if you want to access some other page. Let me know if you have questions.

**Comment by moorepants** [comment]
We have added these pages:

https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.01%3A_How_to_Incorporate_Data_Files_in_Your_Code_Blocks-_For_C

I'm going to call that sufficiently solved. If people want something better, we can open a new issue.
